### ISSUE TITLE
[QUESTION] Manual install procedure?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [xenova/chat-downloader#104]
Hello, I'm using MX Linux (Debian based - it has its own custom repositories updated regularly on top of the stock Debian ones)
When I run the commands in a terminal, I get this:
$ pip install chat-downloader
Collecting chat-downloader
  Could not find a version that satisfies the requirement chat-downloader (from versions: )
No matching distribution found for chat-downloader
  
Is there a way for manually "install" or run the app directly, when Pip doesn't work?
What would be the procedure for that?

**Comment by xenova** [comment]
You should be able to install it locally by running `python setup.py install` from the main directory 👍

However, as the program does have some dependencies if its own, you might face a similar issue when setuptools (the built-in package python uses to install packages) tries to install the necessary packages.

That being said, most of the dependencies are quite standard (e.g. requests), so it shouldn't be a massive issue.
