### ISSUE TITLE
[FEATURE] Option to reject live chat replays

### ISSUE THREAD

**Issue by krichbanana** [xenova/chat-downloader#106]
## Is your feature request related to a problem? Please describe.
I have a program which collects certain Youtube streams and invokes the downloader on them. I check ahead of time if the stream is not post-live, but sometimes the delay between check and downloader invocation (or simply not checking) means I get the chat replay instead of live chat. This is undesirable for a few reasons:
- Downloading chat replay causes requests to be made as fast as your network allows it, creating congestion and possibly causing Youtube to throttle/block any new traffic.
- We want to identify whether the chat was captured live or not, because the replay will differ.
- Live chat and replay chat may get mixed if we are retrying (to my understanding) 
- We might not want chat replays at all

## Describe the solution you'd like
A command-line switch like --reject-download={live,replay}, which would exit with failure if the reject condition is met. This is just a suggestion; you can change the name/usage as you please.

## Describe alternatives you've considered
I check for `is_live or is_upcoming` from Youtube metadata before every download attempt to determine if chat is live ahead of time. However this is a bit time/cpu expensive; it would be faster to start downloading and then fail out quickly if the live is over. It's also a bit impractical to check before one-off downloads.

**Comment by xenova** [comment]
> sometimes the delay between check and downloader invocation (or simply not checking) means I get the chat replay instead of live chat

Does this mean you would prefer to not have any chat downloaded? i.e., to not download any chat if it is not live?

> A command-line switch like --reject-download={live,replay}, which would exit with failure if the reject condition is met

> I check for is_live or is_upcoming from Youtube metadata before every download attempt to determine if chat is live ahead of time. However this is a bit time/cpu expensive; it would be faster to start downloading and then fail out quickly if the live is over. It's also a bit impractical to check before one-off downloads.

I have seen you have implemented this auto downloader [here](https://github.com/krichbanana/ytc-autodownloader) using a shell script. I'm not sure how familiar you are with python, but I believe a lot can be made easier if you were to use the Python module. For example, there is built-in functionality to determine whether a chat is live or a replay.

This would also be much better for "error detection". Instead of searching the file for something like `elif grep -qF 'Chat is disabled' "chat-logs/${outname?}.stderr"; then`, you could just catch the corresponding exception.

I had some time so I whipped up a quick example of what you can do with the python module (this only took like 5 minutes, so I'm sure you could make it way more advanced and suit your needs better. I also think that for more custom solutions like this, using the python module is far better than adding command line arguments.

```python
from chat_downloader import ChatDownloader
from chat_downloader.errors import (
    LoginRequired,
    VideoUnplayable,
    VideoUnavailable,
    ChatDisabled,
    NoChatReplay,
    ChatDownloaderError
)

ids = [
    'p1KolyCqICI',  # past broadcast
    'XWq5kBlakcQ',  # chat disabled
    'vprErlL1w2E',  # members only
    'xxxxxxxxxxx',  # removed/does not exist
    '5qap5aO4i9A',  # live video
]

downloader = ChatDownloader()  # modify this if cookies are necessary

for video_id in ids:

    output_file = f"{video_id}.json"

    try:
        chat = downloader.get_chat(video_id, output=output_file, indent=2)

        if chat.is_live:
            print('(downloader) Downloading chat from live video:', video_id)

            for message in chat:                        # iterate over messages
                # print the formatted message
                chat.print_formatted(message)

        else:
            print('(downloader) Video is not live, ignoring:', video_id)

    except LoginRequired:
        print('(downloader) Private video detected:', video_id)

    except VideoUnplayable:
        print('(downloader) Members only video detected, try again with cookies:', video_id)

    except VideoUnavailable:
        print('(downloader) Removed video detected, giving up:', video_id)

    except (ChatDisabled, NoChatReplay):
        print('(downloader) Disabled chat detected:', video_id)

    except ChatDownloaderError as e:
        print(f'(downloader) {e}:', video_id)

```

---

Let me know if you have any other questions 👍

**Comment by krichbanana** [comment]
I think the module solution is working for me. Only qualm I have is I can't identify if a member video is live or not without cookies, which should be possible since the needed information is provided by YouTube (you just can't download the video).

**Comment by xenova** [comment]
Sure, I can add that functionality. Do you have an example stream I can test on? (e.g., a 24/7 member-only live stream)?

**Comment by krichbanana** [comment]
I checked if a stream had a live live chat the same way I checked it originally: using a patched yt-dlp to check for ```is_live or is_upcoming``` in the produced infodict. The Youtube player API response should have those names, unless the video is private.

As for member streams, the ones I can find are infrequent enough that it may be a few days until you can find a scheduled stream. For a rough search, you can look [here](https://holodex.net/search?q=type,value,text%0Atopic,membersonly,membersonly&type=all), although this will miss streams that aren't scheduled publicly and may include streams that aren't actually going to stream to members-only. (I believe the site just checks the title and guesses.) I don't have a members-only "chat room" link, though they likely exist.

**Comment by xenova** [comment]
Alright, I have finished implementing it in this branch: https://github.com/xenova/chat-downloader/tree/improvements

You can install it using:
```
pip install git+https://github.com/xenova/chat-downloader.git@improvements
```

---

I have changed the downloader program to this:
```python

from chat_downloader import ChatDownloader
from chat_downloader.errors import (
    LoginRequired,
    VideoUnplayable,
    VideoUnavailable,
    ChatDisabled,
    NoChatReplay,
    ChatDownloaderError
)
from chat_downloader.sites import YouTubeChatDownloader


ids = [
    'p1KolyCqICI',  # past broadcast
    'XWq5kBlakcQ',  # chat disabled
    'vprErlL1w2E',  # members only
    '4W9CC2ImQhc',  # live + members only
    'xxxxxxxxxxx',  # removed/does not exist
    '5qap5aO4i9A',  # live video
]

downloader = ChatDownloader()

# Forcefully create a YouTube session
youtube = downloader.create_session(YouTubeChatDownloader)

for video_id in ids:
    details = youtube.get_video_data(video_id)
    is_live = details.get('status') == 'live'

    try:
        output_file = f'{video_id}.json'
        chat = downloader.get_chat(video_id, output=output_file, indent=2)

        if is_live:
            print('(downloader) Downloading chat from live video:', video_id)
            for message in chat:                        # iterate over messages
                # print the formatted message
                chat.print_formatted(message)
        else:
            print('(downloader) Video is not live, ignoring:', video_id)

    except LoginRequired:
        print('(downloader) Private video detected:', video_id)

    except VideoUnplayable:
        live_message = 'Live' if is_live else 'Non-live'
        message = f'(downloader) {live_message} members only video detected, try again with cookies:'
        print(message, video_id)

    except VideoUnavailable:
        print('(downloader) Removed video detected, giving up:', video_id)

    except ChatDisabled:
        print('(downloader) Disabled chat detected:', video_id)

    except ChatDownloaderError as e:
        print(f'(downloader) {e}:', video_id)


```

---

When run, the output should be:
```
$ python examples/downloader.py 
(downloader) Video is not live, ignoring: p1KolyCqICI
(downloader) Disabled chat detected: XWq5kBlakcQ
(downloader) Non-live members only video detected, try again with cookies: vprErlL1w2E
(downloader) Live members only video detected, try again with cookies: 4W9CC2ImQhc
(downloader) Removed video detected, giving up: xxxxxxxxxxx
(downloader) Downloading chat from live video: 5qap5aO4i9A
2021-07-31 18:13:17 | Dustin Görmann: @Lomax I'm doing fine today. thanks for asking. How about you :yougotthis:
2021-07-31 18:13:18 | Nora Ligonniere: Hiii
2021-07-31 18:13:20 | Just for fun Mf: follow me on insta @nsy_
[...]
```

**Comment by krichbanana** [comment]
Just as a note, I just wish to avoid chat replays rather that only download from live livestreams. So I think is_live would be something like `details.get('status') not in {'live', 'upcoming'}`.

Aside from that, I checked over the commit first, and I think the 'premiere' status is a bit confusing. I assumed that this meant to distinguish livestreams from premieres, but from looking at the commit it appears to be set only after the stream concluded. I think what you did is correct behavior, but the docs were a bit misleading on that part.

It'll be a bit before I can fully integrate the changes, so I'll follow up later on how they work.

**Comment by krichbanana** [comment]
I've yet to fully test it but it seems to be working just fine. I'll let you know if anything unusual arises, but I think my issue is solved; thanks for implementing this.

**Comment by xenova** [comment]
> Aside from that, I checked over the commit first, and I think the 'premiere' status is a bit confusing. I assumed that this meant to distinguish livestreams from premieres, but from looking at the commit it appears to be set only after the stream concluded. I think what you did is correct behavior, but the docs were a bit misleading on that part.

Sure, I'll take a look over how I structured the docs again. A video is set to premiere if it is not a live stream, but it has a chat.

This status is set before the extraction takes place, so it should work as expected.

> I've yet to fully test it but it seems to be working just fine. I'll let you know if anything unusual arises, but I think my issue is solved; thanks for implementing this.

Sounds good 👍

**Comment by krichbanana** [comment]
> A video is set to premiere if it is not a live stream, but it has a chat.

This statement suggests that this is true for all premieres, but under the current logic, the status is "premiere" only if it is not "live" or "upcoming", since isLive and isUpcoming still get set normally (even for premieres). The 'premiere' status seems to conflict with those statuses.

It might make more sense to separate the type of video from whether we have an active/replay/missing live chat.

**Comment by xenova** [comment]
The current logic is:
https://github.com/xenova/chat-downloader/blob/e9928f455bc3e92a234b7cc1897fc19e9362756f/chat_downloader/sites/youtube.py#L1437-L1452

> since `isLive` and `isUpcoming` still get set normally (even for premieres) - I believe this is true, but the `isLiveContent` value is only set for live streams and past broadcasts.

For example:
```python
from chat_downloader.sites import YouTubeChatDownloader

session = YouTubeChatDownloader()

ids = [
    'zVCs9Cug_qM', # premiere
    'Ih2WTyY62J4', # replay
    '5qap5aO4i9A' # live
]
for video_id in ids:
    status = session.get_video_data(video_id).get('status')
    print(video_id, status)


```

correctly outputs:
```
zVCs9Cug_qM premiere
Ih2WTyY62J4 vod
5qap5aO4i9A live
```

---

That being said, if you know of an example where this fails, do be sure to let me know :) 👍

**Comment by xenova** [comment]
I've done a bit more testing and there do seem to be some potential issues with premieres that are live or upcoming.

e.g. 2g_nCPVeApk outputs `upcoming`. Perhaps it should be `upcoming_premiere`? Alternatively, I could just have separate fields for `video_type`: `vod`, `premiere`, `video`, `clip`, and live status: `upcoming`, `live`, `replay`?

**Comment by krichbanana** [comment]
Yes, something like the separate fields you suggest would be preferable.

**Comment by xenova** [comment]
Okay, this has been added in 6d0b260d10f266f33c9783832ec365c43e81fa12

`status` is one of: 'live', 'upcoming' or 'past'.
`video_type` is one of 'clip', 'premiere' or 'video'

---

As of typing this,
```python
from chat_downloader.sites import YouTubeChatDownloader

session = YouTubeChatDownloader()

ids = [
    '5qap5aO4i9A', # live video
    'hFh7ww-F624', # upcoming video
    'Ih2WTyY62J4', # past video

    '2hDr4PdkVik', # live premiere
    '2g_nCPVeApk', # upcoming premiere
    'zVCs9Cug_qM', # past premiere
]

for video_id in ids:
    info = session.get_video_data(video_id)
    print(video_id, info['status'], info['video_type'])
```

outputs 
```
5qap5aO4i9A live video
hFh7ww-F624 upcoming video
Ih2WTyY62J4 past video
2hDr4PdkVik live premiere
2g_nCPVeApk upcoming premiere
zVCs9Cug_qM past premiere
```

**Comment by xenova** [comment]
After further testing, these changes have now been included in the latest version (https://github.com/xenova/chat-downloader/releases/tag/v0.1.8)

You can install it using
```
pip install chat-downloader --upgrade
```

---

Let me know if you have any further questions 👍
