### ISSUE TITLE
[FEATURE] Autogenerate filename

### ISSUE THREAD

**Issue by BleachedGorilla** [xenova/chat-downloader#112]
Auto generate filename based on video title would be a great feature. 

Something similar to youtube-dl project filename generation options would be great!

https://github.com/ytdl-org/youtube-dl#output-template

**Comment by xenova** [comment]
Sure, that sounds like a good idea 👍 

I could make it something like `--output {title}.json`. To be more inline with python3 formatting standards

**Comment by xenova** [comment]
Okay, I have implemented this. Can you give it a try and see what you think? (And whether it is ready to merge with master). Currently, `title` and `id` are supported as formatting keys. Channel/username will be added in the future. Other than those,  I don't see a use for any other keys (if you know of another useful key, please let me know 👍 )


https://github.com/xenova/chat-downloader/tree/output

You can install it using:
```
pip install git+https://github.com/xenova/chat-downloader.git@output
```

For example, the option can be used as follows:

### Command line
```
$ chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A -o {id}_{title}.txt
$ chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A -o {id}.txt
$ chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A -o {title}.txt
$ chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A -o example/dir/{id}/{title}.txt
```

### Python
```python
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
downloader = ChatDownloader()

# Using ID
output_format = '{id}.txt'
list(downloader.get_chat(url, output=output_format, max_messages=10))

# Using title
output_format = '{title}.txt'
list(downloader.get_chat(url, output=output_format, max_messages=10))
```

---

Feel free to leave any suggestions/improvements :)

**Comment by xenova** [comment]
After further testing, these changes have now been included in the latest version (https://github.com/xenova/chat-downloader/releases/tag/v0.1.8)

You can install it using
```
pip install chat-downloader --upgrade
```

---

Let me know if you have any further questions 👍

**Comment by Narratur** [comment]
> Okay, I have implemented this. Can you give it a try and see what you think? (And whether it is ready to merge with master). Currently, `title` and `id` are supported as formatting keys. Channel/username will be added in the future. Other than those, I don't see a use for any other keys (if you know of another useful key, please let me know 👍 )

I'd like to suggest `upload_date`, which can be very useful for sorting purposes.
