### ISSUE TITLE
[BUG] Output file not created when using a channel link

### ISSUE THREAD

**Issue by Narratur** [xenova/chat-downloader#116]
## Basic information
- Program version: 0.1.8
- Python version: 3.9.6
- Operating system: Windows 10

Is it possible that output to a .txt or .json file while having the downloader watch a channel is currently broken? As far as I can tell, `chat_downloader https://www.youtube.com/watch?v=sfecivKw_Cw --output chat.txt` will output chat to chat.txt as it should, but `chat_downloader https://www.youtube.com/channel/UCdpUojq0KWZCN9bxXnZwz5w --output chat.txt` will not, chat.txt will never even be created. However, I reverted to 0.1.3 and was able to output to chat.txt through the channel link as normal.

**Comment by xenova** [comment]
Just checked and this is indeed a bug. I will get it fixed this weekend 👍

**Comment by Narratur** [comment]
Awesome, thank you!

**Comment by xenova** [comment]
Fixed 😄👍 I also added a test case to ensure this doesn't happen again.

Let me know if you have any further questions 👍

**Comment by Narratur** [comment]
> Fixed in v0.1.9 😄👍 I also added a test case to ensure this doesn't happen again.
> 
> Let me know if you have any further questions 👍

Thanks, everything’s working as expected now! As a side note I just want to say this project is kind of a god-send and when I searched through the repo for features I was hoping for I found you’d systematically gone through and added pretty much all of them, so very nice work, it’s appreciated. I actually do have a potentially dumb question which probably doesn’t warrant another thread: in the documentation it states `--overwrite` is set to true by default, is there a way I can set this to false in the command line?

**Comment by xenova** [comment]
> Thanks, everything’s working as expected now! As a side note I just want to say this project is kind of a god-send and when I searched through the repo for features I was hoping for I found you’d systematically gone through and added pretty much all of them, so very nice work, it’s appreciated. 

Thanks so much! 😊 

> in the documentation it states --overwrite is set to true by default, is there a way I can set this to false in the command line?

Right, by default, if a file exists with that name, it is emptied. To disable this (i.e., if that file exists, you append to the end), you can specify `--overwrite False`. 

For example, 
```
chat_downloader https://www.youtube.com/channel/UCdpUojq0KWZCN9bxXnZwz5w --output chat.txt --overwrite False
```

should do the trick :)

**Comment by Narratur** [comment]
Ah yes, I thought that wasn't working but it was because I was trying to use it on the old version. Thanks!
