### ISSUE TITLE
[BUG] 'isCustomEmoji'

### ISSUE THREAD

**Issue by vanyamlb** [xenova/chat-downloader#118]
## Basic information
- Program version:  v 0.1.9
- Python version: 3.9.6
- Operating system: MacOS  BigSur 11.4 (I have the same error with Windows 10&11 actually)

## Describe the bug
Error when retrieving and downloading a chat

## Command/Code used

noglob  chat_downloader https://www.youtube.com/watch?v=8T7Q_JtQfR4 --output chat.json

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader linktothevideo  --output chat.json

```
2. Output from the above command:
```
[Traceback (most recent call last):
  File "/usr/local/bin/chat_downloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/cli.py", line 170, in main
    run(**args.__dict__)
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/chat_downloader.py", line 297, in run
    for message in chat:
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 60, in __iter__
    yield from self.chat
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 1141, in _get_chat_messages
    data = self._parse_item(original_item, data)
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 412, in _parse_item
    BaseChatDownloader.remap(
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 280, in remap
    new_value = remap.remap_function(remap_input)
  File "/usr/local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 386, in parse_runs
    'is_custom_emoji': emoji['isCustomEmoji']
KeyError: 'isCustomEmoji'
]
```

## Expected behavior
To download the chat

![image](https://user-images.githubusercontent.com/28903898/131616106-194c4c4f-1cee-4249-8e94-6eb859a1f14c.png)

**Comment by vanyamlb** [comment]
***

edit


I don't know how, but when I updated python and made it default on my MacOS Terminal it worked. Sorry. Please, delete the issue.

**Comment by xenova** [comment]
Hi there 👋  The problem is that you were using an outdated version of chat-downloader. Although you mentioned you were using v0.1.9, that can't be the case as in recent versions, the line `parse_runs` function does not contain `'is_custom_emoji': emoji['isCustomEmoji']`. In fact, it was changed to `'is_custom_emoji': emoji.get('isCustomEmoji', False)` and the `_parse_runs` method is now on line 571 (and not on line 386, as shown above).

Perhaps you had two different python versions with two different version of chat downloader.

---

Either way, glad it's sorted now 👍

**Comment by vanyamlb** [comment]
Sorry for disturbing you again, can we discuss something about the tool here or elsewhere? I have some questions and recommendations about it. It's been used by another tool but it can't be anymore after it's been made more complicated after the iscustomemoji error was fixed. And the tool that was used gives a lot more features in combination with your tool. Thank you so much.

**Comment by xenova** [comment]
Absolutely no worries! 😊 

Sure, you can open up another issue (with the question and/or enhancement tag) and we can discuss there.
