### ISSUE TITLE
't' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by hausofliufeng** [xenova/chat-downloader#124]
## What is your question?
Hi, when i use the "chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A --output chat.json" command on windows, it can grab youtube chat perfectly, but at the end of the script is says "'t' is not recognized as an internal or external command,
operable program or batch file.", and there is no json output, did i miss anything maybe?

## Additional context
![Snipaste_2021-09-13_23-15-06](https://user-images.githubusercontent.com/26713940/133110322-f6ae82c9-5f0a-4da4-82a7-ecdaed3a6bff.jpg)

**Comment by xenova** [comment]
Are you running the command from a batch file? This error does not seem to have anything to do with chat-downloader.

Please can you show a screenshot of the exact command you ran?

My guess is that, somewhere, you have `&t` in your command. This usually means you copied the YouTube url with the &t=123 parameter (used for timestamps).

**Comment by hausofliufeng** [comment]
Problem solved! 

You're right, i have an extra parameter `&t`  copied. I run directly from a terminal. In cmd/cmder the terminal just exucute the command and lead to stop at the end. Window Terminal seems to have an early check and gived the reason. 

![Snipaste_2021-09-14_10-19-23](https://user-images.githubusercontent.com/26713940/133183848-cb9f1bdf-1800-4724-a640-f12b9de24b3d.jpg)

Deleting the parameter, or as suggested, wrapped the & in double quotation like `"&"`  could solve the problem in all terminals.

Thx, xenova
