### ISSUE TITLE
Supechats

### ISSUE THREAD

**Issue by Dramorian** [xenova/chat-downloader#125]
Is there any way/tool to parse all superchats from video with timestamps, currency (original and converted) and color?

**Comment by xenova** [comment]
Yes, this is quite simple with the Python library. As an example:

```python
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=UlemRwXYWHg'
chat = ChatDownloader().get_chat(url, message_groups=['superchat'])

for message in chat:
    money = message.get('money')
    if not money:
        continue

    # Check for valid keys
    # print(message)

    timestamp = message.get('timestamp')

    text = money.get('text')
    currency = money.get('currency')
    amount = money.get('amount')

    colour = message.get('body_text_colour')

    # TODO add conversion logic here
    # e.g. exchange rates
    # converted = rate * amount

    print(f'{timestamp=}, {currency=}, {amount=}, {colour=}')
```

---
There are a few different types of colours, `timestamp_colour`, `body_background_colour`, `header_text_colour`, `header_background_colour`, `body_text_colour`, so you can choose which one you would like to use.


You can print out the message dictionary to see what information is available. For example,
`{'time_in_seconds': 14.477, 'action_type': 'add_chat_item', 'message_id': 'ChwKGkNQN18wY0xoNnVvQ0ZSRUNyUVlkSE1FT193', 'timestamp': 1595761158919935, 'money': {'text': '¥2,000', 'amount': 2000.0, 'currency': 'JPY', 'currency_symbol': '¥'}, 'message': '3D化おめでとう', 'time_text': '0:14', 'timestamp_colour': '#ffffff80', 'body_background_colour': '#f57c00ff', 'header_text_colour': '#ffffffdf', 'header_background_colour': '#e65100ff', 'body_text_colour': '#ffffffdf', 'author': {'name': 'yusan toon', 'images': [{'url': 'https://yt4.ggpht.com/ytc/AKedOLS8mm49oCODnTV68u7ZlJ5jNiTLy9RaqSeziA-0Ng', 'id': 'source'}, {'url': 'https://yt4.ggpht.com/ytc/AKedOLS8mm49oCODnTV68u7ZlJ5jNiTLy9RaqSeziA-0Ng=s32-c-k-c0x00ffffff-no-rj', 'width': 32, 'height': 32, 'id': '32x32'}, {'url': 'https://yt4.ggpht.com/ytc/AKedOLS8mm49oCODnTV68u7ZlJ5jNiTLy9RaqSeziA-0Ng=s64-c-k-c0x00ffffff-no-rj', 'width': 64, 'height': 64, 'id': '64x64'}], 'id': 'UCfn48Bx1rJQbu1xvrwqUJLg', 'name_text_colour': '#ffffffb3'}, 'message_type': 'paid_message'}`
