### ISSUE TITLE
[BUG] Background processes crash when they operate on closed stdin.

### ISSUE THREAD

**Issue by krichbanana** [xenova/chat-downloader#128]
## Basic information
- Program version: 0.1.10
- Python version: 3.9.7
- Operating system: Arch Linux x64, linux package 5.14.6-arch1-1

## Describe the bug
A downloader written using the python module crashes when chat_downloader attempts to flush an inaccessible stdin, which happens after a error in which sleeps before retrying (such as the Service Unavailable error).

### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
```python
    downloader = ChatDownloader(cookies=cookies)
    youtube = downloader.create_session(YouTubeChatDownloader)
    chat = downloader.get_chat(video_id, output=output_file, message_groups=['all'], indent=2, overwrite=False)
    for message in chat:                        # iterate over messages
        pass
```
2. Output, traceback or other information relating to the bug:
```
...
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 283, in __next__
    item = next(self.chat)
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 1668, in _get_chat_messages
    yt_info = self._get_continuation_info(
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 1312, in _get_continuation_info
    self.retry(attempt_number,
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 648, in retry
    timed_input(time_to_sleep)
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/utils/timed_utils.py", line 86, in timed_input
    return _timed_input(timeout, prompt, newline)
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/utils/timed_utils.py", line 76, in posix_timed_input
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

## Expected behavior
A fatal exception should not be raised, and the program should continue without reading input. Ideally, there should be a way to avoid reading stdin at all.

## Additional context/information
The process is a background process; it is impossible to read from the terminal's standard input. Reading stdin will raise an error (or in some cases, will block indefinitely).

**Comment by xenova** [comment]
You should be able to fix this by setting "interruptible_retry" to False. For example, 

```python
downloader = ChatDownloader(cookies=cookies)
youtube = downloader.create_session(YouTubeChatDownloader)
chat = downloader.get_chat(video_id, output=output_file, message_groups=['all'], indent=2, overwrite=False, interruptible_retry=False)
for message in chat:                        # iterate over messages
    pass
```

This was brought up before in https://github.com/xenova/chat-downloader/issues/111 and was fixed then. Let me know if that solves it :)

**Comment by krichbanana** [comment]
I've had a chance to recreate what I did to cause the issue before, and the issue appears to be solved!
