### ISSUE TITLE
[FEATURE] Multiple sources

### ISSUE THREAD

**Issue by SuperSonicHub1** [xenova/chat-downloader#130]
## Is your feature request related to a problem? Please describe.
I'm usually watching Twitch streams from my terminal with mpv and am using chat-downloader as my chat viewer. When streamers are doing collabs, I have to have multiple terminal windows to see each streamer's chat.

## Describe the solution you'd like
You should be able to have multiple URLs as positional arguments. When writing to files, open multiple files. When outputting over standard out, combine chat-downloader's generators using [`itertools.chain`](http://docs.python.org/library/itertools.html#itertools.chain).

## Describe alternatives you've considered
You could have multiple processes with `&`, but that makes them harder to manage. You can also just have multiple terminals open, but that means both chats get less space.

**Comment by SuperSonicHub1** [comment]
Also, if anyone cannot find the time to do this, I'd be happy to write a commit.

**Comment by xenova** [comment]
> Also, if anyone cannot find the time to do this, I'd be happy to write a commit.

Hi there 👋 I'm currently writing university exams, so I am unable to do it (at least for the next 2 weeks), so I would greatly appreciate any help you can provide 😊👍

**Comment by SuperSonicHub1** [comment]
After doing some investigation, I've come to the realization that allowing for multiple sources would require major renovations to this program's architecture, and it all hinges on a couple of lines of code in `chat_downloader/chat_downloader.py`:
```python
    try:
        chat = downloader.get_chat(**chat_params)


        if kwargs.get('quiet'):  # Only check if quiet once
            def callback(item):
                pass
        else:
            def callback(item):
                chat.print_formatted(item)


        for message in chat:
            callback(message)


        log('info', 'Finished retrieving chat messages.')


    except (
        ChatGeneratorError,
        ParsingError,
        TestingException
    ) as e:  # Errors which may be bugs
        pass
```

Each extractor has its own formatting. If you combine all the `Chat`s into one iterator, you can't know where the item info is coming from.

The best course of action would be to just write my own script which just does my own formatting.
