### ISSUE TITLE
[QUESTION] Playing json/rendering chat

### ISSUE THREAD

**Issue by Maj-ew** [xenova/chat-downloader#137]
## What is your question?
With what program can I "render" this chat saver?

## Additional context
So I wanted to play this chat with video of twitch live
At first I thought about using Twitch Downloader and there is feature to render chat as a video.
But I get errors, probably because your program and twitch downloader have different message saving formats and anyways rendering video would be super long on my PC so I wanted like some live player, cause I know that it is fully possible even with emotes
So that's why I ask cause you have to somehow play these chats, otherwise it would be pretty unreadable

**Comment by xenova** [comment]
Unfortunately, that functionality is not currently supported. However, I'm sure it would be possible to develop such a tool to render the chat items as a video.

That being said, if you would like to save the chat as a video, you could always just screen record the chat that is displayed on YouTube.

**Comment by Maj-ew** [comment]
yeah but I would like to see it in any way that is more readable but I don't know how, could you help me?
cause I found your answer and you said

> @HariniP are you sure? I specifically ensure that emojis are read. If you have an issue, you can raise it on the github page and I will take a look at it as soon as possible. Please provide an example of when it fails (e.g. a video and the timestamp) if you create an issue. – 
> Xenova
> Sep 21 '20 at 0:44

https://stackoverflow.com/questions/55789448/is-there-any-way-to-get-the-live-chat-replay-log-history-for-youtube-streaming-v

**Comment by xenova** [comment]
Oh, I think I see what you mean. What you could do is create a custom python script that uses the library and add a "sleep" in between messages. For example,
```python
from chat_downloader import ChatDownloader
import time

url = 'https://www.youtube.com/watch?v=Ih2WTyY62J4' # Change URL here

prev_time = 0
chat = ChatDownloader().get_chat(url, start_time=prev_time)
for message in chat:                        # iterate over messages
    if prev_time is not None and 'time_in_seconds' in message:
        time.sleep(max(message['time_in_seconds'] - prev_time, 0))

    chat.print_formatted(message)           # print the formatted message

    prev_time = message.get('time_in_seconds')

```

---

You can save this as a python file (e.g., `readable.py`) and run it with `python readable.py`. The output should look like this:

https://user-images.githubusercontent.com/26504141/150690975-65f01b51-27f3-4414-b96d-fc5a0e337490.mp4


Now, some "emojis" (which are represented by phrases like :waving_hand: actually sent as text and are rendered in the browser, for example:
![image](https://user-images.githubusercontent.com/26504141/150691052-02c20ecb-904c-409e-8643-1ea77d52db3f.png)
and so cannot be shown in a console.

If you want to render these, you could use a package called emoji (installed using `pip install emoji`) and then use the following code:
```python
from chat_downloader import ChatDownloader
import time
import emoji

url = 'https://www.youtube.com/watch?v=Ih2WTyY62J4' # Change URL here

prev_time = 0
chat = ChatDownloader().get_chat(url, start_time=prev_time)
for message in chat:                        # iterate over messages
    if prev_time is not None and 'time_in_seconds' in message:
        time.sleep(max(message['time_in_seconds'] - prev_time, 0))

    print(emoji.emojize(chat.format(message), use_aliases=True))

    prev_time = message.get('time_in_seconds')

```
**NOTE:** You need to run it in a console that actually supports unicode characters... a well known issue with windows.

This should look something like:

https://user-images.githubusercontent.com/26504141/150691420-6bfdf003-c100-43ca-8ccc-2d67f4971f23.mp4

As you will see, there are some "emojis" which aren't rendered, e.g., :buffering: ... these are custom youtube emotes and thus are not rendered as a unicode character. You can get the image from the message item if you want to display it some other way.

Hope this helps!

**Comment by Maj-ew** [comment]
Thank you I will try that for sure. And thanks so much for all explanations.

**Comment by hizkifw** [comment]
Sorry for resurrecting, but if you're interested in a web player, I have a project that can render the live chat alongside the video just like on YouTube. It supports custom emojis and superchats too.

https://archive.ragtag.moe/player

The source is available on [gitlab/aonahara/archive-browser](https://gitlab.com/aonahara/archive-browser). It's currently still tightly integrated with the website and I don't have a standalone version of it, but you can <kbd>Ctrl</kbd>+<kbd>s</kbd> the player page and it'd work offline.

**Comment by hardworkingcatto** [comment]
Excuse me, how can I import a local file (exported from chat downloader) to the code?

> Oh, I think I see what you mean. What you could do is create a custom python script that uses the library and add a "sleep" in between messages. For example,
> 
> ```python
> from chat_downloader import ChatDownloader
> import time
> 
> url = 'https://www.youtube.com/watch?v=Ih2WTyY62J4' # Change URL here
> 
> prev_time = 0
> chat = ChatDownloader().get_chat(url, start_time=prev_time)
> for message in chat:                        # iterate over messages
>     if prev_time is not None and 'time_in_seconds' in message:
>         time.sleep(max(message['time_in_seconds'] - prev_time, 0))
> 
>     chat.print_formatted(message)           # print the formatted message
> 
>     prev_time = message.get('time_in_seconds')
> ```
> 
> You can save this as a python file (e.g., `readable.py`) and run it with `python readable.py`. The output should look like this:
> 
> Now, some "emojis" (which are represented by phrases like :waving_hand: actually sent as text and are rendered in the browser, for example: ![image](https://user-images.githubusercontent.com/26504141/150691052-02c20ecb-904c-409e-8643-1ea77d52db3f.png) and so cannot be shown in a console.
> 
> If you want to render these, you could use a package called emoji (installed using `pip install emoji`) and then use the following code:
> 
> ```python
> from chat_downloader import ChatDownloader
> import time
> import emoji
> 
> url = 'https://www.youtube.com/watch?v=Ih2WTyY62J4' # Change URL here
> 
> prev_time = 0
> chat = ChatDownloader().get_chat(url, start_time=prev_time)
> for message in chat:                        # iterate over messages
>     if prev_time is not None and 'time_in_seconds' in message:
>         time.sleep(max(message['time_in_seconds'] - prev_time, 0))
> 
>     print(emoji.emojize(chat.format(message), use_aliases=True))
> 
>     prev_time = message.get('time_in_seconds')
> ```
> 
> **NOTE:** You need to run it in a console that actually supports unicode characters... a well known issue with windows.
> 
> This should look something like:
> 
> As you will see, there are some "emojis" which aren't rendered, e.g., :buffering: ... these are custom youtube emotes and thus are not rendered as a unicode character. You can get the image from the message item if you want to display it some other way.
> 
> Hope this helps!
