### ISSUE TITLE
[FEATURE] Batch Download

### ISSUE THREAD

**Issue by HayatoTenryuu** [xenova/chat-downloader#141]
So this is a suggestion directly related to how I would use this tool.

From the looks of the code, it seems like you would download chat from one stream at a time.
Is there a way to implement batch chat logging with the code as it is? It doesn't have to do them
simultaneously, but just copy-pasting a list of links and having it download all the chats to a folder,
naming the file what the stream was named, and once it finishes with one link, it moves on to the next
until the end of the list.

I'm looking at using this tool for archiving purposes, so that's why I was interested in a "batch" feature.
If I could already do this, please let me know how (I'm an amateur with Python...) If it can't be implemented
in the current iteration of this program, it is a feature I'd like to see added if possible.

Thanks!

**Comment by xenova** [comment]
Sure, this can be done 👍 

Does the following implementation solve your needs?

```python
from chat_downloader import ChatDownloader
from chat_downloader.sites.youtube import YouTubeChatDownloader

# Change channel_id here
channel_id = 'UCWxlUwW9BgGISaakjGM37aw'

# Create a downloader
downloader = ChatDownloader()

# Forcefully create a YouTube session
session = downloader.create_session(YouTubeChatDownloader)

# Use the YouTube session to get the channel's videos
videos = session.get_user_videos(channel_id)

# Loop over all the user's videos
for video in videos:
    # Get the chat for the video and save to output file
    chat = downloader.get_chat(video['video_id'], output='output/{title}.txt')
    for message in chat: # Iterate over generator
        pass # Do something with message here, if you wanted to
```

---

The comments should help explain what is happening, but basically get the user's videos and save the chat to a file in a directory called `output` and whose name is the title of the video.

You would save it to a file (e.g., `batch.py`) then run `python batch.py` (provided you have already installed Chat Downloader using `pip install chat-downloader`.

Let me know if you have any other questions 👍

**Comment by HayatoTenryuu** [comment]
One small question, let's say I'm signed in on my youtube account via firefox. And I have a memebership to channel A. If I use this plugin on the same computer with my browser open, would it be able to get member-only stream's chat logs too?

**Comment by xenova** [comment]
Yes the tool is able to fetch member-only stream chat logs, you just have to pass in a valid cookies.txt file. You can follow this tutorial to export a cookies.txt file: https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl and then use the `--cookies <file>` argument when running from the command line, or 
```python
downloader = ChatDownloader(cookies='path/to/cookies.txt')
```

when using the above Python script

**Comment by HayatoTenryuu** [comment]
So, I added the above script in the same area as the other "from" statements in chat downloader.py, and I did everything with cookies.txt that you said to. I left the path in single quotes, but then when I try to run it, I get the error shown in the picture... I tried adding a space, or not using single quotes around the path, but it always ends up the same... Any idea what I've done wrong? I'm on Windows 10 if that helps.


![image](https://user-images.githubusercontent.com/67559652/158107144-d62177f4-b880-4f02-ac18-857ade462204.png)

**Comment by HayatoTenryuu** [comment]
Nevermind! So, I had to go through just about every script in the package and remove the . or .. in the from statement 
(from .sites.youtube import blabla  -> from sites.youtube import blabla)    [don't ask me why, it just works...]

Then I found a couple of modules I was missing (requests and websocket)

After doing all of that one by one, it finally worked. It's running at the moment, I'll see if I get membership stuff and everything, but that's how it works. Also, I had initially put the text above within chatdownloader.py, but realized while debugging that this needed to be its own script. I just named it batch.py and put it in the same folder as chatdownloader.py. This means that in the above script, 'from chat_downloader.sites.youtube import YouTubeChatDownloader' becomes just 'from sites.youtube import YouTubeChatDownloader'

So I'll probably make one more post once it's done working, and I'll see what all it got and what it might've missed. Thanks for all the help though!

**Comment by HayatoTenryuu** [comment]
Ran into one bug/issue - if the video doesn't have a chat, it stops the process with an error message. How would I implement a "if no chat, skip to next video" command?

  File "C:\Users\patri\Desktop\chat-downloader-master\chat_downloader\sites\youtube.py", line 1525, in _get_initial_video_info
    raise NoChatReplay(error_message)
errors.NoChatReplay: Video does not have a chat replay.

**Comment by xenova** [comment]
This is done using `try`... `except` in Python (see https://docs.python.org/3/tutorial/errors.html#handling-exceptions)

and the error you will be catching is `NoChatReplay`.

**Comment by HayatoTenryuu** [comment]
Okay, I was able to use that to have it iterate beyond the video that threw an error. It's still processing them, so I'll let you know how it ends up with that now. Thanks again for all the help!

**Comment by HayatoTenryuu** [comment]
So far it's going well. I noticed that it's significantly slower if I run it in Idle rather than just running the py script. But then I already had several done, so I made a small addition where I can use KeyboardInterrupt to make it skip to the next video. That way, if I ever stop and restart the process, I can skip anything that's already been done.

Having said that, in Idle it did one video per 30 minutes or so, now it's doing one video every 10 minutes. Considering I'm doing an entire channel, that is a very significant amount of time gained. 

If/when it finishes successfully, do you want me to upload my versions of the files to another branch? Especially considering I had to change the import syntax in each file, it probably wouldn't work to just add my batch.py file to what's currently there. But that's up to you.

**Comment by HayatoTenryuu** [comment]
Oof, 92 videos in, Windows Update struck. I don't feel like using KeyboardInterrupt that many times, so I added a loop to skip the number of videos that are complete. I'm really learning a lot about Python by having to use this plugin lol.

**Comment by xenova** [comment]
Windows update always chooses the worst times! Well, it's good to know you are learning more Python haha. If you need any help, feel free to drop a comment.

**Comment by HayatoTenryuu** [comment]
Everything completed perfectly, thanks!
