### ISSUE TITLE
[FEATURE] time_text and time_in_seconds for livestreams

### ISSUE THREAD

**Issue by arcticizza12** [xenova/chat-downloader#142]
Since this feature is only on VODs I think have another idea to implement this for livestreams 

There could be an argument for elapsed time where from the time the command has been run to scrape the live chat, the time_text and time_in_seconds will record how much time it took for that message to be sent and the time will be added on to every chat message that can be sent  

Alternatively (specifically Twitch), you can check the time elapsed on the stream and use that as the time_text and time_in_seconds

**Comment by xenova** [comment]
I suppose that is a valid request - in fact, I've tried it already, but unfortunately there were a lot of inconsistencies when it comes to "guessing" the start time. For example, on YouTube, using the start time of the stream as an offset gave inaccuracies of around 4-10 seconds. This means that running the downloader twice (one during stream and one after) would give different results, making it inconsistent.

So, if you want to include this functionality, I would recommend implementing it yourself using the python module. I could assist you if you needed some help, but unless there is a way to do it consistently, I'm not sure if adding this feature would be the best idea.

**Comment by arcticizza12** [comment]
Ok I did more research and I basically narrowed down what I want, I don't have much experience with Python but I think you could probably help me with this. time_text can be removed because I don't need it, however time_in_seconds is all I need.

Is there a way that I can run how much time has elapsed from the command being put it terminal and message being recorded in the JSON with the time_in_seconds equaling to the elapsed seconds at that moment the message is recorded.

This is assuming the messages are not recorded in batch and are recorded one at a time otherwise this might cause issues

![image](https://user-images.githubusercontent.com/101914627/159135624-b99b5413-8674-4136-a554-788539477e5a.png)

Alternatively the seconds being shown here on the chat_downloader terminal output could also be recorded assuming the 30 seconds is 0 in the time_in_seconds

As for the YouTube stream start time that doesn't matter since I have this downloader running the moment someone starts streaming using scripts on Linux.

**Comment by xenova** [comment]
>Is there a way that I can run how much time has elapsed from the command being put it terminal and message being recorded in the JSON with the time_in_seconds equaling to the elapsed seconds at that moment the message is recorded.

There sure is 👍  You can use the `timestamp` value to get the time the message was sent and subtract the time the script was run to determine the "offset" of the message in seconds.

```python
import time
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url)                   # create a generator

start_time = time.time()                                # get current time
for message in chat:                                    # iterate over messages
    offset = message['timestamp'] / 1e6 - start_time    # calculate offset in seconds
    print(f'{offset:.5f}', '|', message.get('message')) # print offset and message
```

^ Does this do what you need?

**Comment by arcticizza12** [comment]
This is exactly what I need. All I need is to know how to add those seconds in the JSON file as `time_in_seconds` by default for ongoing live streams in the program. I have chat_downloader currently installed as a pip package and if I can add that then I am basically done.

**Comment by xenova** [comment]
Okay I see 👍 . This should do the trick:

```python
import time
from chat_downloader import ChatDownloader
from chat_downloader.output.continuous_write import ContinuousWriter

output_file = 'file.json'
url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'


chat = ChatDownloader().get_chat(url)                   # create a generator
writer = ContinuousWriter(output_file,
                          # indent=4                    # uncomment this if you want it indented
                          )

start_time = time.time()                                # get current time
for message in chat:                                    # iterate over messages

    # Overwrite default time_in_seconds
    message['time_in_seconds'] = message['timestamp'] / \
        1e6 - start_time  # calculate offset in seconds

    writer.write(message, flush=True)  # Write item to file
    chat.print_formatted(message)
```

**Comment by xenova** [comment]
I had to use my "ContinuousWriter" class - since you intend to use it on live streams, it will continuously output to your file.

**Comment by arcticizza12** [comment]
This is honestly perfect, the JSON has formatting issues but I can fix that no problem. You're the best. Do you have a donation link? I would like to fund any other helpful tools to are working on or will make in the future,

**Comment by xenova** [comment]
> This is honestly perfect, the JSON has formatting issues but I can fix that no problem.

Perfect! :) What formatting do you need? If you want to "pretty-print" it, you can set indent=4 (uncomment that line by removing the #). The number you choose specifies how many spaces to put for each indentation level.

> Do you have a donation link? I would like to fund any other helpful tools you are working on or will make in the future,

That's so kind! I have 2 links specified under the "Sponsor" button on the home page at the top: https://ko-fi.com/xenova or https://www.buymeacoffee.com/xenova , but it really isn't necessary :)

**Comment by arcticizza12** [comment]
Oh alright, uncommenting that fixed it, thanks for all the help.

**Comment by xenova** [comment]
No worries 👍  Feel free to open another issue if you have any further questions. I'll close this one for now.
