### ISSUE TITLE
[BUG] error while downloading youtube live chat

### ISSUE THREAD

**Issue by sonytone** [xenova/chat-downloader#144]
## Basic information
- Program version: 0.1.10
- Python version:  3.9.12
- Operating system: Mac os x 11.6.5

## Describe the bug
Error downloading youtube video live chat .

[DEBUG] Python version: 3.9.12 (main, Mar 26 2022, 15:52:10) 
[Clang 13.0.0 (clang-1300.0.29.30)]
[DEBUG] Program version: 0.1.10
[DEBUG] Initialisation parameters: {'headers': None, 'cookies': None, 'proxy': None}
[DEBUG] Created YouTubeChatDownloader session.
[INFO] Site: youtube.com
[DEBUG] Program parameters: {'url': 'https://youtu.be/34Ry9-3egEE', 'start_time': None, 'end_time': None, 'max_attempts': 15, 'retry_timeout': None, 'interruptible_retry': True, 'timeout': None, 'inactivity_timeout': None, 'max_messages': None, 'message_groups': ['messages'], 'message_types': None, 'output': '12Apr2022_RTR2021_raw.json', 'overwrite': True, 'sort_keys': True, 'indent': 4, 'format': 'youtube', 'format_file': None, 'chat_type': 'live', 'ignore': None, 'message_receive_timeout': 0.1, 'buffer_size': 4096}
[DEBUG] Starting new HTTPS connection (1): www.youtube.com:443
[DEBUG] https://www.youtube.com:443 "GET /watch?v=34Ry9-3egEE HTTP/1.1" 200 None

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader -v URL [OPTIONS]
```
2. Output from the above command:
```
[DEBUG] Python version: 3.9.12 (main, Mar 26 2022, 15:52:10) 
[Clang 13.0.0 (clang-1300.0.29.30)]
[DEBUG] Program version: 0.1.10
[DEBUG] Initialisation parameters: {'headers': None, 'cookies': None, 'proxy': None}
[DEBUG] Created YouTubeChatDownloader session.
[INFO] Site: youtube.com
[DEBUG] Program parameters: {'url': 'https://youtu.be/34Ry9-3egEE', 'start_time': None, 'end_time': None, 'max_attempts': 15, 'retry_timeout': None, 'interruptible_retry': True, 'timeout': None, 'inactivity_timeout': None, 'max_messages': None, 'message_groups': ['messages'], 'message_types': None, 'output': '12Apr2022_RTR2021_raw.json', 'overwrite': True, 'sort_keys': True, 'indent': 4, 'format': 'youtube', 'format_file': None, 'chat_type': 'live', 'ignore': None, 'message_receive_timeout': 0.1, 'buffer_size': 4096}
[DEBUG] Starting new HTTPS connection (1): www.youtube.com:443
[DEBUG] https://www.youtube.com:443 "GET /watch?v=34Ry9-3egEE HTTP/1.1" 200 None 
......
```
If the output is too long, you can attach a text file or remove output which does not constitute to the problem.

### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
```python
# python code
```
2. Output, traceback or other information relating to the bug:
```
[output or description]
```

## Additional context/information
Add any other context or information about the problem here.

**Comment by xenova** [comment]
Hi, the video you are trying (https://www.youtube.com/watch?v=34Ry9-3egEE) does not have a live chat.
