### ISSUE TITLE
[BUG] add-banner type is concatented

### ISSUE THREAD

**Issue by krichbanana** [xenova/chat-downloader#150]
See here:
https://github.com/xenova/chat-downloader/blob/ff9ddb1f840fa06d0cc3976badf75c1fffebd003/chat_downloader/sites/youtube.py#L981

I was attempting to add support for the new redirect-type banner and found that the second line had merged with the third line (and so on...), which I discovered was due to a missing comma on the second line (clearly a copy-paste error). This should be fixed.

Or, I could finish with my banner changes and make a PR, but that would take much longer as I still need to clean up my code.

**Comment by xenova** [comment]
Oh yes you are correct! Could you perhaps make a PR? I know it's a small change, but I'm on my laptop right now and haven't got the environment set up correctly.
