### ISSUE TITLE
[BUG] Installation doesn't work

### ISSUE THREAD

**Issue by the-overdriven** [xenova/chat-downloader#153]
## Basic information
- Program version: none
- Python version: Python 3.7.2rc1
- Operating system: Windows 10
- pip version: newest, just updated

## Command/Code used
```
C:\Users\xyz>pip install chat-download
ERROR: Could not find a version that satisfies the requirement chat-download (from versions: none)
ERROR: No matching distribution found for chat-download
```

## Expected behavior
It should install chat-downloader.

**Comment by xenova** [comment]
As stated in the README (https://github.com/xenova/chat-downloader#installation),
the correct command is:
```
pip install chat-downloader
```
