### ISSUE TITLE
[FEATURE] Zoom chat support

### ISSUE THREAD

**Issue by upintheairsheep** [xenova/chat-downloader#159]
Example videos:
https://zoom.us/rec/play/6ccrIuigqG83GIaT4wSDAv59W9W5J_-s1HUe_6UPykq3V3hVN1emMucTYLEJiA87rIkEPcGptB0Dp_dH
https://zoom.us/rec/play/65V5deGq-Do3T9bHuASDAv4tW420f_ms1iIb-vIKzEqzUiEFNFWiYONAN-vRvNmKnlg6z95Y4mNQ9QJQ
https://zoom.us/rec/play/75Usc7j8rjg3E92S4gSDAf95W9S9K6-sg3dP_voImR60WiEHYVSmYrsbNwNE1_6-jwlwLx5cg1IeyjM

**Comment by xenova** [comment]
Looks simple-enough to add. Will put it on the list (and hopefully implement it soon).

**Comment by upintheairsheep** [comment]
> Looks simple-enough to add. Will put it on the list (and hopefully implement it soon).

After adding it, can you fix this YT-DLP Twitch chat bug where it only downloads the first few messages? https://github.com/yt-dlp/yt-dlp/issues/3664

**Comment by upintheairsheep** [comment]
And support for TikTok comments https://github.com/yt-dlp/yt-dlp/issues/4012 SoundCloud comments https://github.com/yt-dlp/yt-dlp/issues/4015 And this TikTok yt-dlp bug https://github.com/yt-dlp/yt-dlp/issues/3776

**Comment by upintheairsheep** [comment]
And port zoom support to dlp as well. Sorry for the burden.

**Comment by upintheairsheep** [comment]
I’m an archivist and those YT dlp changes would be lovely.

**Comment by upintheairsheep** [comment]
> Looks simple-enough to add. Will put it on the list (and hopefully implement it soon).

Just as a reminder, it has been 5 months since I made this issue.

**Comment by xenova** [comment]
I've added support for zoom.us 👍 Can you test it and see if it works as intended? If so, I will release it.

You can install directly from the repo using 
```bash
pip install --upgrade git+https://github.com/xenova/chat-downloader.git
```
