### ISSUE TITLE
[BUG] Some youtube members only streams fail with "Unable to parse initial video data" (reason: _YT_INITIAL_BOUNDARY_RE regex doesn't match)

### ISSUE THREAD

**Issue by ArkahnX** [xenova/chat-downloader#160]
## Basic information
- Program version: 0.1.10
- Python version: 3.10.4
- Operating system: Windows Version	10.0.19044 Build 19044

## Describe the bug
Some Youtube members streams would fail to be read because the regex in _YT_INITIAL_BOUNDARY_RE no longer matched the html response

## Command/Code used
changed the regex to match the changes found, instead of a meta variable, a head variable was found instead
file: `chat_downloader/sites/youtube.py`
old: `_YT_INITIAL_BOUNDARY_RE = r'\s*(?:var\s+meta|</script|\n)'`
new: `_YT_INITIAL_BOUNDARY_RE = r'\s*(?:var\s+(?:meta|head)|</script|\n)'`

### If running from the command line, provide the following:
Response is way too long, but here is a copy of the html response that ended up being the issue. you can see that after the _YT_INITIAL_PLAYER_RESPONSE_RE match, the variables are in a different order compared to non-members streams. (judging by the fact that normal streams work without any changes)
https://gist.github.com/ArkahnX/c19fd0a5c3d0ffb56cf32d9a5d0be642

**Comment by xenova** [comment]
Please update to the latest version (`pip install chat-downloader --upgrade`), which is v0.2.0a, not v0.1.10

**Comment by ArkahnX** [comment]
I am quite a bit out of date then, sorry about that!
