### ISSUE TITLE
[QUESTION] Comment downloader?

### ISSUE THREAD

**Issue by upintheairsheep** [xenova/chat-downloader#162]
## What is your question?
Will you make a separate comment downloader in the future, or add support for various site’s comments in the future for this project?
## Additional context
Add any other context or screenshots here.

**Comment by krichbanana** [comment]
you likely want to use yt-dlp, with yt-dlp --write-comments. It supports a fair number of websites, as long as those comments are associated with a page hosting video or audio.

**Comment by upintheairsheep** [comment]
I know yt-dlp and plan on writing comment extractors.
