### ISSUE TITLE
[QUESTION] Error or incorrect use?

### ISSUE THREAD

**Issue by Buu987** [xenova/chat-downloader#163]
Do i use it right or is there a Issue? 
This is from the example iam useing.

> from chat_downloader import ChatDownloader
> 
> url = 'https://www.youtube.com/watch?v=36YnV9STBqc'
> chat = ChatDownloader().get_chat(url)       # create a generator
> for message in chat:                        # iterate over messages
>     chat.print_formatted(message)           # print the formatted message

This is the error message i get

> Traceback (most recent call last):
>   File "/home/pi/Desktop/ChatDownloader/Chat.py", line 4, in <module>
>     chat = ChatDownloader().get_chat(url)       # create a generator
>   File "/home/pi/.local/lib/python3.9/site-packages/chat_downloader/chat_downloader.py", line 259, in get_chat
>     formatter = ItemFormatter(params['format_file'])
>   File "/home/pi/.local/lib/python3.9/site-packages/chat_downloader/formatting/format.py", line 37, in __init__
>     with open(default_path) as default_formats:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/lib/python3.9/site-packages/chat_downloader/formatting/custom_formats.json'

I try it on a raspberry pi 4 if that's important

**Comment by xenova** [comment]
You somehow are missing the custom_formats.json file (https://github.com/xenova/chat-downloader/blob/master/chat_downloader/formatting/custom_formats.json)

Try download it and place it in the folder it says above.

How did you install the project? Using pip, git, or another way?

**Comment by Buu987** [comment]
I used pip. I'll try it tomorrow and thanks for the help.

**Comment by Buu987** [comment]
It works now. Thanks for the help.
