### ISSUE TITLE
[BUG] Emoji combinations are erroneously stripped from messages.

### ISSUE THREAD

**Issue by krichbanana** [xenova/chat-downloader#168]
## Basic information
- Program version: 0.2.0 (plus local modifications for new message types)
- Python version: 3.10.6
- Operating system: Arch Linux
- Site: YouTube

## Describe the bug
Unicode supports combining multiple characters like so: 🙏+ 🏼 = 🙏🏼. YouTube handles these by providing custom emoji graphics for these combinations as it does for uncombined emojis. These "combined" emojis have no "name" field (since it's not one emoji), but it does have an emoji_id field.

chat_downloader handles these nameless fields by dropping them, due to the logic [here](https://github.com/xenova/chat-downloader/blob/657e56eeec4ebe5af28de66b4d3653dbb796c8c1/chat_downloader/sites/youtube.py#L603), which only adds an emoji with a defined name.

My proposed solution: make name optional, just like the other fields, and only rely on the presence of emoji_id. Also, if name is undefined, then use emoji_id for the message instead, as a fallback.

## Output
Raw emoji received from YouTube (via `yt-dlp --write-subs --sub-langs live-chat`), which was completely stripped from the output json:
```json
{
  "emoji": {
    "emojiId": "🙏🏼",
    "image": {
      "thumbnails": [
        {
          "url": "https://www.youtube.com/s/gaming/emoji/0f0cae22/emoji_u1f64f_1f3fc.svg"
        }
      ],
      "accessibility": {
        "accessibilityData": {
          "label": "🙏🏼"
        }
      }
    }
  }
}
```

## Expected behavior
The emoji should still be saved in the JSON output, and the message should still properly render when using the default formatter.

**Comment by AtticFinder65536** [comment]
While working on a similar project, I came across 🆘 `:SOS_button:` / `:sos:` not having a shortcut/searchTerms so it is not only limited to grapheme clusters/emoji combinations it seems. I would avoid relying on shortcut/searchTerms being present for non-custom emoji. Another solution could be to use the emoji library to get the CLDR short name/alias from emojiId and use that.

**Comment by xenova** [comment]
@krichbanana Thanks for the report! Can you provide a link for me to test with?

PS: Sorry for the late response... been quite busy recently 😓

**Comment by AtticFinder65536** [comment]
Not OP, but I see it at the beginning of 7KwGABMjpMU with the "2⃣" messages, message ID CkUKGkNJN2gtN0tGOXZJQ0ZWTGl3UW9kbVI0Q2hREidDTHpGOTVpRjl2SUNGU21BbFFJZEpqSU1fZzE2MzEzMzMxMDY3Mjc%3D in Tiw1tYMMNig with "👏🏼" and message ID ChwKGkNMbVBrZXpoNnVvQ0ZSVmJXQW9kUG5VQjhn in the UlemRwXYWHg unit test with "㊗".

**Comment by xenova** [comment]
Fixed 👍  Let me know if you still have any issues
