### ISSUE TITLE
[QUESTION] Multiple videos

### ISSUE THREAD

**Issue by jhenion209** [xenova/chat-downloader#169]
## What is your question?
Is there a way to run the tool against a playlist or youtube channel?

## Additional context
I have used youtube-dl and yt-dlp to batch download the chat logs of a youtube channel, which saves in json format for each video.

Command used:
yt-dlp --no-download --playlist-items 1-10 --part --write-subs --sub-langs live_chat --no-overwrites -o "%(release_date)s_%(id)s.%(ext)s" <URL>

The output format saves the filenames as YYYYMMDD_<video-id>.json. Is there a way to do this with chat-downloader? Your output is much easier to read than the json format.

**Comment by xenova** [comment]
Although this functionality isn't currently built in to the command-line application, you can use the python library to implement this. As an example:

```python
from chat_downloader import ChatDownloader
from chat_downloader.sites import YouTubeChatDownloader
from chat_downloader.errors import ChatDownloaderError

downloader = ChatDownloader()

playlist_url = 'https://www.youtube.com/playlist?list=PLLGT0cEMIAzcd5XagsMwz22-NFPmToKIP'

youtube = downloader.create_session(YouTubeChatDownloader)
items = youtube.get_playlist_items(playlist_url)

params = {
    # NOTE: max_messages is only here for demonstration purposes
    'max_messages': 100
}
for item in items:
    print(f"Retrieving chat for {item['video_id']}: {item['title']}")

    try:
        chat = downloader.get_chat(
            item['video_id'], **params)  # create a generator
        for message in chat:  # iterate over messages
            chat.print_formatted(message)

    except ChatDownloaderError as e:
        # Skip video if there is an error (e.g., Chat disabled)
        print('ERROR:', e)

    print()

```

*Note:* Make sure you are on the latest version of ChatDownloader (>=0.2.1), since I changed the `get_playlist_items` method
