### ISSUE TITLE
[QUESTION] What is this Twitch Client_ID

### ISSUE THREAD

**Issue by tomy137** [xenova/chat-downloader#173]
## What is your question?
Hey there, thanks for your chat-downloader. It's very usefull ! 

I tried to change the client_id for Twitch VOD chats requests with mine. But the V5 API reject my request. Why is yours working ? I'm pretty curious about that. Where did you find that client_id ? Can I get one on my own ? 

![image](https://user-images.githubusercontent.com/2952029/195044378-9623b4bd-0357-4fc3-81b1-a8a6b76f8ccb.png)

Thanks in advance for your anwser ! 
Have a good day !

**Comment by TheTechRobo** [comment]
I'm 99% sure this is using GQL, which is Twitch's undocumented API as used by the website. It's GraphQL, and you can find the client id in the requests sent and received by your browser.

**Comment by xenova** [comment]
Hi there. It is the client ID for unauthenticated requests. That is, if you are logged out, all requests will be made with that client ID (you can test it out by opening twitch in incognito)
