### ISSUE TITLE
[BUG] Incomplete data (KeyError: 'name')

### ISSUE THREAD

**Issue by AG4lyf** [xenova/chat-downloader#175]
## Basic information
- Program version: 0.2.0
- Python version: 3.10.5
- Operating system: win11 (22h2)

## Describe the bug
youtube will return incomplete data on some specific streams. 
apparently if any one with no name (idk how this is possible yt ?) like - https://www.youtube.com/channel/UC_oQ7X9HmE3Xuaa_wFerOqg post a comment author key is not added

Test Case stream link - https://www.youtube.com/watch?v=-JU0rbfPECY

## Additional context/information
there is nothing the library can do to prevent this from happening other than passing ```{'author':{'name': "" , .......}}``` or mention this kind stuff in docs or have a test case for such thing.?

**Comment by xenova** [comment]
Hmmm, interesting... I'll look into it, thanks!
