### ISSUE TITLE
[QUESTION] Message Groups (YT Gifted Memberships)

### ISSUE THREAD

**Issue by vampiricwulf** [xenova/chat-downloader#178]
## What is your question?
Under what category are gifted memberships under? 
Is there a way to tell it to just log everything?

**Comment by xenova** [comment]
The current groups defined can be found here: https://github.com/xenova/chat-downloader/blob/master/chat_downloader/sites/youtube.py#L433-L479

As for logging everything, you should be able to do so if you set message types to "all"

**Comment by vampiricwulf** [comment]
I used every message group minus "placeholder" and it didn't log when gifts were sent or received, is it not getting parsed?

Should I set message groups to `['all']` as well or just mark types as `['all']`? Looking at this it seems to check both. 
https://github.com/xenova/chat-downloader/blob/master/chat_downloader/sites/common.py#L404-L405

**Comment by xenova** [comment]
Hmmm, gifts are a new thing, right? It might not be getting parsed. Can you send the video url?

**Comment by vampiricwulf** [comment]
Yes, here's one I was able to find: https://youtu.be/TFHxcbaikpU?t=5618

**Comment by vampiricwulf** [comment]
Another thing to note is that when telling it to capturing everything, superchat messages are captured twice in a row. I believe it's because superchat and ticker overlaps.

**Comment by vampiricwulf** [comment]
```log
2022-11-28 18:13:08 | 

2022-11-28 18:13:15 | recipient: was gifted a membership by gifter
...
2022-11-28 19:11:36 | 

2022-11-28 19:11:43 | recipient 2: was gifted a membership by gifter
```
So it does log gifting when using ['all'] in message groups, but it only catches the received message and the "Gifter has given out X memberships!" is an empty line.

You can test it on https://www.youtube.com/watch?v=cb0h-KbpDo8 and the gifting is at 5:22:20 with the receiving at 5:22:35.

**Comment by xenova** [comment]
Thanks for the info! I'll try get this sorted as soon as possible
