### ISSUE TITLE
Twitch chats can´t be got anymore

### ISSUE THREAD

**Issue by mangu75** [xenova/chat-downloader#187]
I was using this library as the documentation indicates, but it is not working anymore to get chat from twitch streamings. It is probably because twitch API v5 has been migrated.

Do you know some other alternative to get the chat from VDOS?

**Comment by xenova** [comment]
Yes - this was fixed yesterday in version 0.2.3 (see https://github.com/xenova/chat-downloader/issues/186)

You can update to this version using:
`pip install chat-downloader --upgrade`
