### ISSUE TITLE
[BUG] chat-downloader: command not found

### ISSUE THREAD

**Issue by varvello** [xenova/chat-downloader#190]
## Basic information
- Program version: chat-downloader
- Python version: Python 3.10.9  - pip 22.3.1
- Operating system: OSX 12.6.1

## Describe the bug
I successfully installed chat-downloader via `pip install chat-downloader`, but when I launch it from prompt it shows:  chat-downloader: command not found

**Comment by xenova** [comment]
You must run it with `chat_downloader ...`  (`_` not `-`)
