### ISSUE TITLE
how to fix [ERROR] 404 Not Found ?

### ISSUE THREAD

**Issue by malubululv5** [xenova/chat-downloader#195]
## Basic information
- Program version:0.2.3
- Python version:3.11.1
- Operating system:windows 10

## Describe the bug
[ERROR] 404 Not Found

## Command/Code used
chat_downloader https://www.youtube.com/live/K6KVtSdLNQE?feature=share
## Screenshots
https://postimg.cc/wyY3mN5r

**Comment by xenova** [comment]
Oh wow I did not know that URL format was possible. I went to the link and it redirects to https://www.youtube.com/watch?v=K6KVtSdLNQE (and `chat_downloader` works with that format)

When youtube.com/watch is not used, it usually means it is meant for a channel (e.g., youtube.com/nasa). 

I'll look into it and see what other tools (like yt-dlp) use. In the meantime, can you just use the youtube.com/watch url?

**Comment by xenova** [comment]
Just checked, and yt-dlp (version 2023.01.06) doesn't support that URL format. For example: 
```
$ yt-dlp -j  https://www.youtube.com/live/K6KVtSdLNQE
WARNING: [generic] Falling back on generic information extractor
```

**Comment by TheTechRobo** [comment]
Fun fact: `youtube.com/watch/VIDEO_ID` is also recognised.

**Comment by malubululv5** [comment]
> Oh wow I did not know that URL format was possible. I went to the link and it redirects to https://www.youtube.com/watch?v=K6KVtSdLNQE (and `chat_downloader` works with that format)
> 
> When youtube.com/watch is not used, it usually means it is meant for a channel (e.g., youtube.com/nasa).
> 
> I'll look into it and see what other tools (like yt-dlp) use. In the meantime, can you just use the youtube.com/watch url?

oh tysm
