### ISSUE TITLE
[BUG] wrong param order in readme instructions

### ISSUE THREAD

**Issue by ernestd** [xenova/chat-downloader#205]
in the README file
chat-downloader url --output file
should be
chat-downloader --output file url

## Basic information
- Program version:
- Python version:
- Operating system:

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader -v URL [OPTIONS]
```
2. Output from the above command:
```
[output goes here]
```
If the output is too long, you can attach a text file or remove output which does not constitute to the problem.

### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
```python
# python code
```
2. Output, traceback or other information relating to the bug:
```
[output or description]
```

## Additional context/information
Add any other context or information about the problem here.

**Comment by xenova** [comment]
Hi. Both orders work. 👍
