### ISSUE TITLE
Chat downloader is broken

### ISSUE THREAD

**Issue by gadi-playstream-gg** [xenova/chat-downloader#207]
- Program version: 0.2.4
- Operating system: AWS Lambda :) 

seems like the  chat downloader is not working anymore. 
The word on the internet is that twitch changed their intergrity checks for GQL

anyone else is having this issue?

**Comment by aiyulu1** [comment]
i have this issue +1

**Comment by nio-p** [comment]
same here !!

**Comment by nio-p** [comment]
@xenova 

Could you please fix this problem?
I really need  your help 🙇

**Comment by hellishvictor** [comment]
Here (Win x64 SP1) it doesn't download the whole chat, but only the first 50 lines of a VOD.

**Comment by nio-p** [comment]
@xenova 

> this only affects VODs
maybe not.

You mean, Livesteam = streaming now?
If so, this video is streaming now and I can not fetch chats correctly.
https://www.twitch.tv/videos/1811939415

I only get 58 chats but more chats this stream.

**Comment by xenova** [comment]
The workaround proposed [here](https://github.com/lay295/TwitchDownloader/commit/be2c9f1ac5b51f88ee1f149e70f05f22a1d6f23a) is to update the client ID:
"kimne78kx3ncx6brgo4mv6wki5h1ko" -> "kd1unb4b3q4t58fwlpcbzcbnm76a8fp"
(both of which are public)

If you replace it here:

https://github.com/xenova/chat-downloader/blob/10d8f1fc74a0555f6a50d3353b70ea5a24fb3bce/chat_downloader/sites/twitch.py#L210

does that work for you? Seems to work fine on my end.

**Comment by nio-p** [comment]
@xenova 

Works fine !!!!!
I really appreciate it !!

**Comment by xenova** [comment]
> Works fine !!!!!
> I really appreciate it !!

Great! I'll try make a proper release later today 👍

**Comment by gadi-playstream-gg** [comment]
How’s changing the id solves the issue? Can u explain?

**Comment by nio-p** [comment]
@gadi-playstream-gg 

For your reference:
https://github.com/lay295/TwitchDownloader/issues/704#issuecomment-1535595293

Changing the id is just workaround.
Old id `kimne78kx3ncx6brgo4mv6wki5h1ko` is maybe restricted from Twitch so we use new id that is not restricted.

**Comment by hellishvictor** [comment]
I did changed the CLIENT_ID ("kimne78kx3ncx6brgo4mv6wki5h1ko" with "kd1unb4b3q4t58fwlpcbzcbnm76a8fp") on the file "twitch.py" on "\Python\Lib\site-packages\chat_downloader\sites\" and the chat downloaded of the VOD is still incomplete :(

**Comment by hellishvictor** [comment]
> @hellishvictor
> 
> VOD url please. I will check it !
> 
> Edit: My env is macOS 13.3.1 (a) (22E772610a), python 3.10.

Forget it, it works like a charm. Thank you!

**Comment by aiyulu1** [comment]
> The workaround proposed [here](https://github.com/lay295/TwitchDownloader/commit/be2c9f1ac5b51f88ee1f149e70f05f22a1d6f23a) is to update the client ID: "kimne78kx3ncx6brgo4mv6wki5h1ko" -> "kd1unb4b3q4t58fwlpcbzcbnm76a8fp" (both of which are public)
> 
> If you replace it here:
> 
> https://github.com/xenova/chat-downloader/blob/10d8f1fc74a0555f6a50d3353b70ea5a24fb3bce/chat_downloader/sites/twitch.py#L210
> 
> does that work for you? Seems to work fine on my end.

thx, that work for me

**Comment by xenova** [comment]
Thanks for the report 👍 

v0.2.5 is out now, and this fixes the issue. https://pypi.org/project/chat-downloader/0.2.5/

You can upgrade using
```
pip install chat-downloader --upgrade
```

**Comment by vvibee** [comment]
@xenova 
Thanks for that, new client ID works fine.
There is another question for me, which is how could we get client-id? 
Is that the same client-id we get when registered a application on twitch api?

**Comment by xenova** [comment]
If you really want to use your own client ID, I believe you can find the one linked to your account by inspecting the network traffic in your browser's dev tools. However, that may cause similar issues to what was reported here. In future, it may be necessary to generate the associated integrity key needed for requests.

The ones used by this tool are public and are used by unauthenticated clients (i.e., logged out users).

Is there a specific reason you want to use a different client ID?

**Comment by vvibee** [comment]
@xenova 
Yes, your answear is what I confused. 
If there would be integrity key necessary in future, then generate access token to pass integrity check could be next work to be done. 
Here is twitch integrity check generator I found that comes with same problem: https://github.com/Kappador/twitch-integrity
Twitch restricted it's ID from getting access token.
I wonder if using different ID that applied by user themself to generate access token, could it be easier to pass intergrity check and has lower probability to be restricted by Twitch?

**Comment by gadi-playstream-gg** [comment]
@xenova I've upgraded but it doesn't seem to solve the issue.
Anyone else still having issues?

**Comment by nio-p** [comment]
@gadi-playstream-gg 

My app that uses this library works correctly.

Can you paste your full logs?
