### ISSUE TITLE
[BUG] Urgent - Chat downloader broken again

### ISSUE THREAD

**Issue by gadi-playstream-gg** [xenova/chat-downloader#210]
## Basic information
- Program version: 0.2.6
- Operating system: Linux / arm64

## Describe the bug
ChatDownloader().get_chat(chatLink);
failing to get any stream's chat data , for example : 
chatLink =  https://www.twitch.tv/videos/1827185140

**Comment by xenova** [comment]
So kind of Twitch to completely change everything :') Fixing now.

**Comment by xenova** [comment]
Should be fixed in v0.2.7 (https://pypi.org/project/chat-downloader/)

Update with:
```bash
pip install --upgrade chat-downloader
```

Let me know if you have any other questions.
