### ISSUE TITLE
Exception: "Expecting value: line 1 column 1 (char 0)" when trying to get Twitch chat

### ISSUE THREAD

**Issue by Toby237** [xenova/chat-downloader#211]
- Program version: 0.2.6
- Python version: 3.7
- Operating system: Windows 10

When trying to use the program on Twitch messages an exception is thrown:
"Expecting value: line 1 column 1 (char 0)"

The code used to call the code in the library that causes this exception is this:
from chat_downloader import ChatDownloader
ChatDownloader().get_chat(str(videoUrl)) # 'videoUrl' is an URL to a Twitch video

It seems that the exception is thrown somewhere around L303 in "chat_downloader.py"

**Comment by xenova** [comment]
Same as https://github.com/xenova/chat-downloader/issues/210. Fixing now.

**Comment by xenova** [comment]
Should be fixed in v0.2.7 (https://pypi.org/project/chat-downloader/)

Update with:
```bash
pip install --upgrade chat-downloader
```

Let me know if you have any other questions.
