### ISSUE TITLE
Duplicate super chat, membership purchase; Print issue; FileNotFoundError

### ISSUE THREAD

**Issue by ebir25** [xenova/chat-downloader#34]
- `superchat_ticker` is not ignored when output format is json.
- Superchat without message display as 'None' after print. (like this: `[01:23] *$5.00* authorZ: None`)
- `liveChatMembershipItemRenderer` is an auto-message but after print is look like normal message.
- `FileNotFoundError` when parent folder of output filepath not exist.

(Sorry for my bad english.)

**Comment by xenova** [comment]
Thanks for posting! 👍 

Can you post an example of a video which does this? (e.g. `[01:23] *$5.00* authorZ: None`)

`superchat_ticker` messages are meant to be written to the JSON file. However, the next version of the software will allow users to specify the exact types of messages which they want to retrieve (e.g. superchat ticker vs. normal superchat)

Although it is normal for a `FileNotFoundError` to occur when the directory does not exist, I can perhaps make it automatically create a folder if it does not exist.

"liveChatMembershipItemRenderer is an auto-message" - can you explain what you mean by "auto-message"? I think it appears in the chat, so it should be shown, right?

**Comment by ebir25** [comment]
`python3 chat_replay_downloader.py -message_type all -from 4840 -to 4845 https://youtu.be/YQAcWQ8mlUQ` the yellow superchat

auto-message i mean it not type & send by author, it is a notification when author purchase Membership.
If you print a membership purchase message: `[12:34] (New member) authorZ: Welcome to abc!` (abc: custom membership name)
And I cant tell if is just a normal text message or a membership purchase message.
So I just want a new format for membership purchase message. Something like this: `[12:34] *Membership* (New member) authorZ: ...`

**Comment by xenova** [comment]
Okay I see what you mean. This will be added in an upcoming version.

**Comment by pupkinvaska** [comment]
Have Duplicate super chat issue too. Dupliceted row in .csv differs from the 1st one in that the `ticker_duration` field has some value.

**Comment by xenova** [comment]
> Have Duplicate super chat issue too. Dupliceted row in .csv differs from the 1st one in that the `ticker_duration` field has some value.

This might be intended. YouTube returns two messages for some superchats:
1. One for the actual message in chat, and
2. One that appears as a "ticker" with a duration.

For the most part, these are the same, which is why it appears to be a duplicate (e.g. the name would be the same).

In the next version of the software, you will be able to exclude these "ticker" messages.

Tickers: 
![image](https://user-images.githubusercontent.com/26504141/102113630-ed4d6200-3e41-11eb-8f98-95a827ca78a6.png)


Superchat:
![image](https://user-images.githubusercontent.com/26504141/102113666-f5a59d00-3e41-11eb-8ef0-ab103ae90377.png)

**Comment by xenova** [comment]
The required functionality has been added to the latest version of the software:

---

> In the next version of the software, you will be able to exclude these "ticker" messages.

You can now use the `--message_groups` argument to specify what messages you want to retrieve. For example,
```
chat_downloader https://youtu.be/YQAcWQ8mlUQ --start_time 4840 --end_time 4845 --message_groups "messages superchat"
```

For YouTube (as of right now), you can specify any number of the following message groups: `messages`, `superchat`, `tickers`, `banners`, `donations`, `engagement`, `purchases`, `mode_changes`, `deleted`, `bans`, `placeholder`.

---

> So I just want a new format for membership purchase message. Something like this: `[12:34] *Membership* (New member) authorZ: ...`

This can be done with the new `--format` and `--format_file` arguments. For examples, see https://github.com/xenova/chat-downloader/issues/22#issuecomment-871749575 and https://github.com/xenova/chat-downloader/issues/45#issuecomment-871742623
