### ISSUE TITLE
Message types

### ISSUE THREAD

**Issue by artiction** [xenova/chat-downloader#56]
Not really an issue, but I've realized that the script isn't grabbing superchats. I feel like it's `--message_types superchat_message` but the script isn't working after being run. But then again, can I know what to use for grabbing both text and superchats? Since `all_message` is definitely wrong.

**Comment by xenova** [comment]
Hi there. The correct usage is as follows:
```
chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A --message_groups "messages superchat"
```

Note this uses `--message_groups`. If you want more control, you can specify `--message_types`, for example:
```
chat_downloader https://www.youtube.com/watch?v=n5aQeLwwEns --message_types "text_message paid_message membership"
```


This is my fault as I am still busy writing the documentation. The keys are message groups and the elements in the lists are message types. So, the message group `superchat` contains `membership_item`, `paid_message` and `paid_sticker`. Here are the different message groups and message types for YouTube in the meantime.


```
_MESSAGE_GROUPS = {
    'messages': [
        'text_message'  # normal message
    ],
    'superchat': [
        # superchat messages which appear in chat
        'membership_item',
        'paid_message',
        'paid_sticker',
    ],
    'tickers': [
        # superchat messages which appear ticker (at the top)
        'ticker_paid_sticker_item',
        'ticker_paid_message_item',
        'ticker_sponsor_item',
    ],
    'banners': [
        'banner',
        'banner_header'
    ],

    'donations': [
        'donation_announcement'
    ],
    'engagement': [
        # message saying live chat replay is on
        'viewer_engagement_message',
    ],
    'purchases': [
        'purchased_product_message'  # product purchased
    ],

    'mode_changes': [
        'mode_change_message'  # e.g. slow mode enabled
    ],

    'deleted': [
        'deleted_message'  # old: 'deleted_state_message'
    ],
    'bans': [
        'ban_user'
    ],

    'placeholder': [
        'placeholder_item'  # placeholder
    ]
}
```

**Comment by artiction** [comment]
It's alright, I mean everyone here depends on your script in the first place. So thank you for making this.
Also, I prioritize text messages, although having both superchats and members are also nice. Thanks for the quick reply!

**Comment by xenova** [comment]
@artiction I wrote a short guide on how to use message groups and types: https://github.com/xenova/chat-downloader/wiki/Message-groups-and-types

Hope it helps!
