### ISSUE TITLE
[BUG] Youtube Membership welcome messages produce JSON object in place of message text

### ISSUE THREAD

**Issue by awused** [xenova/chat-downloader#59]
## Basic information
- Program version: Current pip version
- Python version: 3.8
- Operating system: Linux/Fedora

## Describe the bug
Instead of a simple text string the "message" field for membership welcome messages is a nested object. This seems to be a regression with the newest version.

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader "https://www.youtube.com/watch\?v\=ie5oTaH3nAk" --message_groups all --output "output.json" -v
```

One particular example message from that chat replay, though this applies to both add_live_chat_ticker_item and add_chat_item.
```
        "message": {
            "message": "Welcome to \u6850\u751f\u4f1a!"
        },
        "message_id": "ChwKGkNLRDV0YV9tMXU0Q0ZZMm13UW9kVlBnQjhR",
```

## Expected behavior
All "message" fields should be simple strings
```
        "message": "Welcome to \u6850\u751f\u4f1a!"
        "message_id": "ChwKGkNLRDV0YV9tMXU0Q0ZZMm13UW9kVlBnQjhR",
```

**Comment by xenova** [comment]
Hi there - yes you are correct, this is a bug. Let me get that fixed!

**Comment by xenova** [comment]
Let me know if that fixes it! 😃

**Comment by awused** [comment]
Seems to be fixed.
