### ISSUE TITLE
[FEATURE] Get live chat when user goes live

### ISSUE THREAD

**Issue by artiction** [xenova/chat-downloader#62]
## Is your feature request related to a problem? Please describe.
So, some streamers have stream rooms up before they stream, right?
And some of them even disable the live chat before the stream actually begins, like an hour or less before it actually starts.

## Describe the solution you'd like
So, rather than manually trying to re-enter the command line or refreshing sites like Youtube to see if the live chat's available to public, I'm suggesting some kind of retry system to keep the command running and grab the live chats when it starts.

## Additional context
Sorry if what I'm requesting is already a thing with python scripts, like below? gist.github.com/plieningerweb/39e47584337a516f56da105365a2e4c6

I'll try the link above first to run the feature that I want, although I can only copy paste stuffs since I don't understand much other than texts. So, I'm hoping this feature could be added if I fail to run it. Also, I'm going to sleep so yeah

**Comment by xenova** [comment]
Sure I can add something like this! 👍

**Comment by artiction** [comment]
Hi, I'm actually not sure what to do if the code becomes buggy after I tamper with it, so I'll just wait for the feature. Sorry to bother you, though.

**Comment by xenova** [comment]
> Hi, I'm actually not sure what to do if the code becomes buggy after I tamper with it, so I'll just wait for the feature. Sorry to bother you, though.

No worries. I am currently working on improving documentation (and some other improvements), but I will get to it as soon as possible. If you don't mind, can you take a look at https://github.com/xenova/chat-downloader/issues/61#issuecomment-780898860? Just so I can close that issue. Thanks!

**Comment by alnj** [comment]
I already posted this, but I'm not sure if I accidentally deleted my post or if there's a network bug.
I made this shell script to achieve what you're trying to do.

```sh
#!/bin/sh
channel="$1"

get_live_url() {
	_channel="$1"

	_video_code=$(youtube-dl --list-formats --playlist-end 1 "$_channel/live" | grep MPD)
	if [ -n "$_video_code" ]; then
		_url=${_video_code#*be] }
		_url="https://www.youtube.com/watch?v=${_url%:*}"
		echo "$_url"
	fi
}

while live_url=$(get_live_url "$channel"); do
	if [ -n "$live_url" ]; then
		chat_downloader "$live_url"
	else
		sleep 60
	fi
done
```

**Comment by artiction** [comment]
Cool, I'll check it tomorrow, thanks for the reply!

**Comment by xenova** [comment]
Great stuff @alnj 😃 

This functionality has actually already been implemented in the [docs](https://github.com/xenova/chat-downloader/tree/docs) branch and will be released as soon as possible. It currently works with a channel url/id (e.g. https://www.youtube.com/channel/UCSJ4gkVC6NrvII8umztf0Ow or just UCSJ4gkVC6NrvII8umztf0Ow), and I will add support for custom urls shortly (e.g. https://www.youtube.com/c/chilledcow or https://www.youtube.com/user/xxx)

**Comment by artiction** [comment]
@alnj I'll be honest, I have no idea how to work this script out, where should I put the channel / video url?
@xenova When is this gonna be ready? And will it work with only the channel url, like the next upcoming livestream will automatically be saved? If yes, that sounds like the perfect feature for me, so thank you.

**Comment by xenova** [comment]
I am quite busy during the week with university work, so I can only continue working on it over the weekend.

**Comment by alnj** [comment]
@artiction I initially made it for myself so it's a shell script that won't work on Windows (not sure what OS you're using).
After making it executable with `chmod +x filename.sh` you can call it with `./filename.sh [channel URL goes here]`. This will run continuously, running chat_downloader on every public video, but you can also make it run on just the next one if you add a `break` or `return` in a new line after the chat_downloader line.

**Comment by xenova** [comment]
Sorry for the long wait... but I finally got around to adding this to the latest version (it was in the beta for the past few months).

You can now use the channel id of a user to search for live streams. If they are not streaming (i.e., no upcoming live stream or ongoing live stream), you will get the following message:
```
[INFO] There are no active or upcoming livestreams with a live chat. Retrying again in 30 seconds.
```

For example,
```
$ python -m chat_downloader https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw
[INFO] Site: youtube.com
[INFO] Retrieving chat for "UC-lHJZR3Gqxm24_Vd_AJ5Yw".
[INFO] There are no active or upcoming livestreams with a live chat. Retrying again in 30 seconds.
```

Every 30 seconds, it retries and once the channel goes live, the chat will be captured.

Let me know if you have any further questions! 😃
