### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by craigmilliken** [xenova/chat-downloader#63]
## Basic information
- Program version: v0.0.4 (latest)
- Python version: 3.9.1
- Operating system: MacOS Catalina 10.15.7

## Describe the bug
I'm following the ReadMe instructions at https://github.com/xenova/chat-downloader#python

```python
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url)       # create a generator
for message in chat:                        # iterate over messages
    print(chat.format(message))             # print the formatted message
```

I'm substituting https://www.youtube.com/watch?v=5qap5aO4i9A for https://www.youtube.com/watch?v=fpXXFiG1BXs, and I'm able to print the chat replay. However, superchats are omitted from this payload. Is this a bug, or am I not structuring the query correctly to display *both* superchats and regular chats together (or independently)?

Side note: Nice work on this very useful and interesting tool!

**Comment by xenova** [comment]
Hi there. You are missing the `--message_groups` (or `--message_types`) argument.

```python
url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(
    url,
    message_groups=['messages', 'superchat']
)                                   # create a generator

for message in chat:                # iterate over messages
    print(chat.format(message))     # print the formatted message
```

This is mostly an issue with the lack of documentation - something I am working extremely hard to fix ([docs branch](https://github.com/xenova/chat-downloader/tree/docs))! I am also working on many other features ([error messages](https://github.com/xenova/chat-downloader/tree/errors), [better testing](https://github.com/xenova/chat-downloader/tree/random_testing))at the same time.

Let me know if you have any other questions 👍

**Comment by craigmilliken** [comment]
Nice! Thanks for putting me on the right path -- felt like I was missing something. All great stuff and look forward to following the updates to this repo. Best!

**Comment by xenova** [comment]
Thanks! :)
