### ISSUE TITLE
[FEATURE] Structured Superchat amount

### ISSUE THREAD

**Issue by mikoim** [xenova/chat-downloader#64]
## Is your feature request related to a problem? Please describe.
Currently, the Superchat amount is provided as string. To aggregate its data, it should cause parsing text. If YouTube provides structured data, it should be better passing as it.

## Describe the solution you'd like
```python
"¥1,000"

{amount: 1000, currency: "JPY"}
```

**Comment by xenova** [comment]
I actually have plans to implement exactly that! :)
https://github.com/xenova/chat-downloader/blob/643dc3bfea6d83a536fbf08dd6d67c04a67802de/chat_downloader/sites/youtube.py#L420

I wrote it to myself as a comment, but I will implement it as soon as possible.

**Comment by atnjqt** [comment]
Would be great to get amount broken into currency & val... I can quickly get USD currency knowing they all start with `$`... 

``` python
chat_df = pd.read_json('./data/raw/chat-downloader-run-outfile.json)
chat_df['USD'] = chat_df[chat_df.amount.str[0] == '$'].amount.str.replace('$','').astype(float)
```

Some other examples of non-USD include the following, anecdotally (I do not know how many currencies superchats support):
``` python
non_usd_chat_df = chat_df[chat_df.amount.str[0] != '$']
non_usd_chat_df.amount.value_counts()
``` 

> CA$20.00     2
> PLN 50.00    1
> £10.00       1
> R$2.00       1
> SEK 50.00    1
> CA$20.99     1
> CA$50.00     1
> CA$10.00     1
> CA$100.00    1
> £5.00        1

**Comment by mikoim** [comment]
| raw 	| code 	|
|------	|------	|
| A$   	| AUD  	|
| R$   	| BRL  	|
| CA$  	| CAD  	|
| €    	| EUR  	|
| £    	| GBP  	|
| HK$  	| HKD  	|
| ₹    	| INR  	|
| ¥    	| JPY  	|
| ₩    	| KRW  	|
| MX$  	| MXP  	|
| NZ$  	| NZD  	|
| NT$  	| TWD  	|
| $    	| USD  	|

**Comment by xenova** [comment]
@mikoim Thanks for the info 👍 . Do you have a source for where you got this list? Are these all the possibilities?

**Comment by mikoim** [comment]
@xenova The table is aggregated from observed data. It does not contain all currencies.

**Comment by xenova** [comment]
Okay 👍 I haven't seen a currency other than the ones you have mentioned. Everything else is just the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 3-character code (e.g. 'CHF', 'COP', 'HUF', 'PHP', 'PLN', 'RUB', 'SEK', 'PEN', 'ARS', 'CLP', 'NOK', 'BAM', 'SGD')

**Comment by xenova** [comment]
Thoughts on #67 before I merge?

Superchat messages with an amount attached are now parsed, returning a `money` dictionary containing:
- text: text used for display purposes
- amount: float value of money
- currency: ISO 4217 currency code (e.g. USD) 
- currency_symbol: currency symbol (e.g. $)

---

As an example use-case:
```python
from chat_downloader import ChatDownloader


totals = {
    'member_count': 0,
    'paid_message': {},
    'paid_sticker': {}
}

try:
    url = 'https://www.youtube.com/watch?v=LgYq0xORY3w'
    chat = ChatDownloader().get_chat(url, message_groups=['superchat'])

    for message in chat:
        print(chat.format(message))
        message_type = message.get('message_type')
        if message_type == 'membership_item':
            totals['member_count'] += 1
        else:
            money = message.get('money')
            if money:
                currency = money['currency']

                if currency not in totals[message_type]:
                    totals[message_type][currency] = 0

                totals[message_type][currency] += money['amount']
finally:
    print('\nMembers gained:', totals['member_count'], end='\n\n')
    for paid_type in ('paid_message', 'paid_sticker'):
        print(paid_type)
        for currency in totals[paid_type]:
            print('  {}: {:.2f}'.format(currency, totals[paid_type][currency]))
        print()
```
This sums up the amounts of different currencies and prints this information out (along with number of members who joined during a stream). Example output is as follows:
```
Members gained: 95

paid_message
  USD: 3533.87
  GBP: 276.86
  MXN: 180.00
  AUD: 210.45
  NOK: 95.00
  INR: 440.00
  HKD: 100.00
  HUF: 3393.00
  EUR: 30.46
  CAD: 206.75
  BRL: 5.00
  DKK: 135.00
  RUB: 1000.00
  BYN: 5.00
  NZD: 0.99
  RON: 5.00
  HRK: 5.00
  PEN: 6.90
  PHP: 2500.00

paid_sticker
  INR: 19.00
  GBP: 2.00
  USD: 14.97
  CAD: 4.99
```

**Comment by mikoim** [comment]
Nice! How about introducing a parameter to supply an additional currency table?

**Comment by xenova** [comment]
> How about introducing a parameter to supply an additional currency table?
I would argue that the user should never need to supply their own currency table. The tool should do this by default. There should not be a situation where a user has different currencies to what YouTube provides. If other currencies get introduced in the future, they will be added then.

**Comment by mikoim** [comment]
I agree with you. If I found a new one, I'll add them to the build-in table.

**Comment by xenova** [comment]
Great 👍 (you can always just make a PR with the new currency added).

So I'm good to merge?
