### ISSUE TITLE
[QUESTION] Records collected from live YT chat is different from data collected from archived VOD chat data

### ISSUE THREAD

**Issue by itchyknobs** [xenova/chat-downloader#70]
## What is your question?
It seems like when we run the tool live, the chat collected is different from what is archived in past VODs. Is this because chat is deleted in archived VODs? Or is this because the tool is collecting Top Chat only; instead of all live chat?

## Additional context
comparison of number of rows collected on broadcast between live and archived VOD chat is about 10k rows (20% data) for a broadcast.

**Comment by xenova** [comment]
Hi there. Yes, this is indeed a frequently asked question (e.g. https://github.com/xenova/chat-downloader/issues/35). I have also got numerous emails about it.

When creating the chat replay, YouTube - for some reason - decides to **not** show everything. They choose to hide some messages.

The tool is only able to get messages which appear on the chat replay (which is shown on YouTube). If you go to the video's page, you should see the exact same messages as the program retrieves. There is no way (official or unofficial) to get all messages from a live chat replay. The only way to guarantee that all messages are retrieved is to download the chat while it is live.
