### ISSUE TITLE
[QUESTION] Is the amount of membership_item correct ?

### ISSUE THREAD

**Issue by teisseire117** [xenova/chat-downloader#74]
Hi,

I'm trying to count the amount of new memberships subscribed during a Youtube livestream, and I'm a little surprised at the results I'm getting.

I know that some messages in the chat can only be seen during the live stream, and cannot be retrieved later with your library, and I'm wondering if it's the same for Memberships ?

__________________________________________________

Example, for bJjNnsWK_4U we can see there are 30 new memberships and 91 superchats
On the same channel, for 1AIMAiWweOA there are 1172 new memberships and 48 superchats.
Those two videos are only 1 month apart, same time length, approx. same amount of views

That's just one example, there are a lot of discrepancies between videos from a same channel. So I'm wondering if I can trust those numbers or not

**Comment by xenova** [comment]
Hi there - yes, the number of items you get should be correct (should be exactly what you see from the video's page). The streamer must have enabled memberships around that time.

If you go to [1AIMAiWweOA](https://www.youtube.com/watch?v=1AIMAiWweOA), you'll see:
![image](https://user-images.githubusercontent.com/26504141/108560782-ee998000-7305-11eb-935f-50ff7908d2d9.png)

But if you go to [bJjNnsWK_4U](https://www.youtube.com/watch?v=bJjNnsWK_4U), you'll see:
![image](https://user-images.githubusercontent.com/26504141/108560920-1f79b500-7306-11eb-8a4d-de9cdaf6e6ba.png)

---

If you take more samples I am sure you will see clearer trends.

**Comment by teisseire117** [comment]
> Hi there - yes, the number of items you get should be correct (should be exactly what you see from the video's page). The streamer must have enabled memberships around that time.
> 
> If you go to [1AIMAiWweOA](https://www.youtube.com/watch?v=1AIMAiWweOA), you'll see:
> ![image](https://user-images.githubusercontent.com/26504141/108560782-ee998000-7305-11eb-935f-50ff7908d2d9.png)
> 
> But if you go to [bJjNnsWK_4U](https://www.youtube.com/watch?v=bJjNnsWK_4U), you'll see:
> ![image](https://user-images.githubusercontent.com/26504141/108560920-1f79b500-7306-11eb-8a4d-de9cdaf6e6ba.png)
> 
> If you take more samples I am sure you will see clearer trends.

Script is doing stats for all the videos on the channel, it usually takes few hours to complete, once it's done I'll come back put the the result for each day/month here if it seems odd

**Comment by xenova** [comment]
> > If you take more samples I am sure you will see clearer trends.
> 
> Script is doing stats for all the videos on the channel, it may take a couple of hours to complete, once it's done I'll come back put the the result for each day/month here if it seems odd

Okay great 👍

**Comment by teisseire117** [comment]
Alright so the issue is not your script, it is just Youtube not displaying all new Memberships.

I calculated the amount of memberships subscribed by checking the chat / superchat / membership_items and it's vastly under-estimated

![DlfmLK8](https://user-images.githubusercontent.com/43145883/108616511-3277ac80-740e-11eb-9729-d848661b8136.png)

If we just take in consideration membership_item it returns 8,416 for 6 months of streaming at 30 000 viewers / stream ~, it's unbelievably low, especially considering how insane the superchats were.

But by checking the chat/superchat we can see there were in fact approx. 123,915 memberships subscribed during the whole period.

**Comment by xenova** [comment]
It is quite unfortunate that YouTube hides a lot of data when showing the chat replay. The only logical reason I can think of is to reduce client side lag (and perhaps alleviate server stress?).

The only 100% accurate way is to run the tool while the user is live. This should get every message that was sent (including memberships + superchats)

I am adding some functionality to the tool which allows users to get live chat as soon as a channel goes live (#62) and will be released as soon as possible. This will definitely help with these types of calculations.

**Comment by teisseire117** [comment]
> It is quite unfortunate that YouTube hides a lot of data when showing the chat replay. The only logical reason I can think of is to reduce client side lag (and perhaps alleviate server stress?).
> 
> The only accurate way - it seems - is to run the tool while the user is live. This should get every message that was sent (including memberships + superchats)
> 
> I am currently adding some functionality to the tool which allows users to get live chat as soon as a channel goes live (#62) and will be released as soon as possible. This will definitely help with these types of calculations.

oh, that could be indeed a nice feature

**Comment by alnj** [comment]
Linux-only, but I use this shell script to watch for livestreams and run chat-downloader every time a livestream is going on.

```sh
#!/bin/sh
channel="$1"

get_live_url() {
	_channel="$1"

	_url=$(youtube-dl --list-formats --playlist-end 1 "$_channel/live" | grep MPD)
	[ -z "$_url" ] && return
	_url=${_url#*be] }
	_url="https://www.youtube.com/watch?v=${_url%:*}"
	echo "$_url"
}

while live_url=$(get_live_url "$channel"); do
	if [ -n "$live_url" ]; then
			chat_downloader "$live_url"
	else
		sleep 60
	fi
done
```
