### ISSUE TITLE
[FEATURE] Output chat directly to file in simple, plain text (no metadata)

### ISSUE THREAD

**Issue by MVail88** [xenova/chat-downloader#77]
## Is your feature request related to a problem? Please describe.
I'm using Windows 10's CMD to run Chat Downloader. Because Windows is terrible, that thing has some problems with Unicode characters. They don't display properly in the CMD window, and attempts to redirect the output using > causes any Unicode characters to disappear completely from the file they are being redirected to. I am able to copy and paste the chat from the CMD window into a text file which then displays the characters correctly, but this is always cumbersome and for very active chats on long streams it is impossible due to line limits with CMD.

## Describe the solution you'd like
I'd like an option for the output that this program already supports to write to a file directly the exact same thing it already prints to the console. As in, I don't care about properly formatted and labeled metadata about each chat message that can be processed by me, I just want what the chat message, name of the user, and the time it was sent, much like you would see in the stream's actual chat.

## Describe alternatives you've considered
It's very possible that somewhere documentation exists on how to get CMD to do this, and I'm sure it isn't a problem for almost any other operating system. If anyone has those solutions, feel free to post them here, but maybe also include a reference to that in documentation for Chat Downloader. Alternatively, if this feature already exists, point me in the direction of documentation for it so that I may use it, but perhaps display this documentation more prominently since I imagine it would be a common use case.

**Comment by xenova** [comment]
Sure I can add something like this 😃👍

**Comment by MVail88** [comment]
I found that post as well and it didn't solve my issue. I wish I knew _why_ it didn't solve my issue since it seems like it should, but that's neither here nor there. Thank you for considering this feature request.

**Comment by xenova** [comment]
While I add this feature to the command line, you could use the following python program to do what you want:
```python
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url)                   # create a generator


with open('output.txt', 'a+', encoding='utf-8') as output_file:
    for message in chat:                                # iterate over messages
        formatted_message = chat.format(message)
        print(formatted_message)
        print(formatted_message, file=output_file)      # write to a file

```

**Comment by xenova** [comment]
This functionality has been added in latest versions. 👍 

Using `--output text.txt` will now output exactly as shown in the console. For example,

```
chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A --output chat.txt
```
will output something like:
```
2021-07-01 17:41:22 | shiny saji: @k.s😂
2021-07-01 17:41:22 | Steph Glz: 15
2021-07-01 17:41:23 | Xx_burro_pixel_lolplayer: potooooooooooooooooo
2021-07-01 17:41:24 | Mikasa Ackerman: im very concerned
2021-07-01 17:41:24 | Adidas Nature: awesome music love it man ❤️😘 and feels alone 🥺
2021-07-01 17:41:25 | Oifil 1: 21
2021-07-01 17:41:26 | Kaulo Soldaat: 20
2021-07-01 17:41:31 | Morse Code: can't believe that girl is writing for a year! I would've died writing that much.
```

Let me know if you have any further questions.

**Comment by MVail88** [comment]
Finally got a chance to test this. Works exactly as I expected it to. Thank you very much!
