### ISSUE TITLE
[BUG] Cannot download superchat and new member information from Youtube

### ISSUE THREAD

**Issue by EvanSky-lab** [xenova/chat-downloader#80]
## Basic information
- Program version: 0.0.8
- Python version: 3.7.3
- Operating system:Windows 10

## Describe the bug
Maybe Youtube has changed its API about them.Because some similar tools also can't download them.I can only download common chats by chat-downloader.

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader -v https://www.youtube.com/watch?v=Dwv4-LDKG8Q
```

2. Output from the above command:

https://github.com/xenova/chat-downloader/files/6083551/2.txt

## Expected behavior
I can get  superchat information from キヤブ丸 at about 9:38. The content is ネジキチャレンジ待ってます！ 

Sorry, my English is poor.

**Comment by xenova** [comment]
Have you tried using the `--message_groups` command?

```
chat_downloader -v https://www.youtube.com/watch?v=Dwv4-LDKG8Q --message_groups "messages, superchat"
```

**Comment by EvanSky-lab** [comment]
OK,thank you so much！I thought the default setting can get all messages...sorry

**Comment by EvanSky-lab** [comment]
> Have you tried using the `--message_groups` argument?
> 
> ```
> chat_downloader -v https://www.youtube.com/watch?v=Dwv4-LDKG8Q --message_groups "messages, superchat"
> ```

OK,thank you so much！I thought the default setting can get all messages...sorry
