### ISSUE TITLE
[BUG] attempted relative import with no known parent package

### ISSUE THREAD

**Issue by kenshin657** [xenova/chat-downloader#82]
## Basic information
- Program version: 0.0.8
- Python version: 3.8.5
- Operating system: Windows 10

## Describe the bug
After the running the code below I get the error found in the title

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
python chat_downloader.py -v https://www.youtube.com/watch?v=d5lP9i5OUM8
```
2. Output from the above command:
```
[output goes here]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\chat_downloader\chat_downloader.py", line 9, in <module>
    from .metadata import __version__
ImportError: attempted relative import with no known parent package
```

## Expected behavior
Chat Logs to be printed out in Command Line

**Comment by xenova** [comment]
Hi there. 👋 You are trying to a execute regular python file, however, this is a python module.

If you have installed the program via pip
```
pip install chat_downloader
```

You can run it with 
```
chat_downloader https://www.youtube.com/watch?v=d5lP9i5OUM8
```

Otherwise, if you are in the folder, you can run it with
```
python -m chat_downloader https://www.youtube.com/watch?v=d5lP9i5OUM8
```
