### ISSUE TITLE
[QUESTION] How to save to .txt file?

### ISSUE THREAD

**Issue by ilya-s-h** [xenova/chat-downloader#83]
## What is your question?
How to save chat to .txt file from twitch? 
I'm a video editor and don't know much about code. Your program helps me a lot. 
The only thing I would like to see a more detailed description of the use for people like me.

## Additional context
--format FORMAT       Specify how messages should be formatted for printing, default uses site default 
  --format_file FORMAT_FILE  /// How exactly can I replace the FORMAT_FILE phrase?
                        Specify the format file to choose formats from
                        
Many thanks! I really look forward to your answer!

**Comment by xenova** [comment]
How would you like the text to be saved? If you just want the output as it is in the console, you can just use the `output` argument as follows:

```
chat_downloader https://www.twitch.tv/ludwig --output test.txt
```

where obviously "test.txt" can be changed to the file name of your choice. Let me know if you have any other questions 👍

**Comment by ilya-s-h** [comment]
I want to get a .txt file, but no JSON information. Just simple information from the chat.

In this format:
0:11 | (GLHF Pledge) starchlordop: pog

But not in this format:
{'message_id': 'c3f02ae1-10b1-49f3-a713-efbdae2f9992', 'timestamp': 1616778254692000, 'time_in_seconds': 11.992, 'author': {'display_name': 'starchlordop', 'id': 664010560, 'name': 'starchlordop', 'type': 'user', 'bio': None, 'created_at': 1616093863543686, 'images'....

Very grateful for your help. You answer very quickly!

**Comment by xenova** [comment]
Oh you are right I haven't updated the tool to do that yet! The .txt output is just on my development branch. In the meantime, you can use standard output redirection then:

```
chat_downloader https://www.twitch.tv/ludwig > test.txt
```

Let me know if that works better! 😄 ... I'll update the tool as soon as possible to include it as I mentioned above.

**Comment by ilya-s-h** [comment]
Yes, now everything works exactly as I need it! Thank you so much for your work! 
You save me tens of hours of work. 
Your version of the program is the only one that gives the comment time in the video - this is very important to me. 
I will definitely support your project with money one day! Keep up your great work!
