### ISSUE TITLE
[BUG] interpretation of expiration time 0 in cookies.txt 

### ISSUE THREAD

**Issue by 9001** [xenova/chat-downloader#84]
## Basic information
- Program version: v0.0.8
- Python version: 3.8.2 and 3.9.2
- Operating system: macOS and Windows 10 x64 LTSC

## Describe the bug
Okay so I'm not familiar with cookies.txt, so I'm not sure whether Youtube-DL or chat-downloader is to blame... but I think it would be a good idea to replicate Youtube-DL's behavior for the sake of convenience.

When a cookie in cookies.txt has expiry time 0, the cookie is not included (i think) in http-requests. This means that most cookies set by Youtube-DL will not make it, as Youtube-DL interprets 0 as infinite and produces cookies.txt accordingly.

This is problematic as YouTube now requires the CONSENT cookie (at least in the EU), and chat-downloader does not generate this. Some currently accepted values are `YES+NO.no+V11+BX` and `YES+cb.20210328-17-p0.en+FX+754`.

## Command/Code used

```
$ python3 -m youtube_dl --cookies cookies.txt youtube.com/watch?v=XyL6bhHsNhQ
[...]

$ cat cookies.txt
.youtube.com	TRUE	/	FALSE	0	CONSENT	YES+[...]
.youtube.com	TRUE	/	TRUE	1617258888	GPS	1
.youtube.com	TRUE	/	TRUE	1632808888	VISITOR_INFO1_LIVE	[...]
.youtube.com	TRUE	/	TRUE	0	YSC	[...]

$ python3 -m chat_downloader -c cookies.txt -o ars.json youtube.com/watch?v=XyL6bhHsNhQ
[INFO] Site: youtube.com
Traceback (most recent call last):
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/cli.py", line 170, in main
    run(**args.__dict__)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/chat_downloader.py", line 273, in run
    chat = downloader.get_chat(**chat_params)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/chat_downloader.py", line 207, in get_chat
    chat = self.get_chat(**original_params)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/chat_downloader.py", line 166, in get_chat
    info = self.sessions[site.__name__].get_chat(**params)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/sites/youtube.py", line 1393, in get_chat
    return self.get_chat_by_video_id(match.group('id'), kwargs)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/sites/youtube.py", line 1367, in get_chat_by_video_id
    initial_info = self._get_initial_video_info(video_id)
  File "/Users/ed/Library/Python/3.9/lib/python/site-packages/chat_downloader/sites/youtube.py", line 906, in _get_initial_video_info
    raise ParsingError(
chat_downloader.errors.ParsingError: Unable to parse initial video data. <!doctype html><html lang="en" dir="ltr"><head><base href="https://consent.youtube.com/"><meta name="referrer" content="origin"><link rel="canonical" href="https://consent.youtube.com/m"><meta name="viewport" content="initial-scale=1,minimum-scale=1,maximum-scale=5,width=device-width"><link rel="shortcut icon" href="//www.google.com/favicon.ico"><script data-id="_gd" nonce="[...]
```

## Expected behavior
When the CONSENT cookie in cookies.txt is modified to have an expiry time in the future, the chat download succeeds

## Additional context/information
I didn't check whether the cookies are actually included or not, or whether the 0 causes incorrect formatting or something, so that part is just an assumption. But youtube is not happy :)

EDIT: nothing interesting in `-v` either, aside from the redirect URL to https://consent.youtube.com:443 -- it includes some session-tracking URL parameters (they don't seem too related to the final cookie value)

**Comment by xenova** [comment]
Support for generating consent cookies has been added in the latest version (v0.1.1). So, this should fix this issue too. Would you be able to confirm? You shouldn't need to pass a cookies file in anymore either. 😃

**Comment by 9001** [comment]
yup, that takes care of the actual problem, so don't have to worry about this anymore :>

welcome back btw!

**Comment by xenova** [comment]
> yup, that takes care of the actual problem, so don't have to worry about this anymore :>
>
> welcome back btw!

Awesome! 😄 Super happy to be back. 😃
