### ISSUE TITLE
[FEATURE] emote support for YouTube

### ISSUE THREAD

**Issue by lekoOwO** [xenova/chat-downloader#87]
Will chat-downloader support youtube emote download?

It'll be nice to see it stored in ChatDownloader instance and available when exported.

Thank you!

e.g.
```python
x = ChatDownloader(...)

# Do some download stuff

x.emotes # {":hii:": "https://.../hii.png", ":hey:": "https.."}

**Comment by 9001** [comment]
if it's good enough to have the emotes saved into a local folder, then it's possible to do this with softchat... but unfortunately it requires some setup (sorry!)

the [readme](https://github.com/9001/softchat/blob/hovedstraum/README.md) has steps to enable more additional features, but the things you definitely need are:
* install [fontforge](https://fontforge.org/en-US/) and, if you are on linux, the python bindings for it
* install [imagemagick](https://imagemagick.org/script/download.php)
* create a folder named `noto-hinted` and download [NotoSansCJKjp-Regular.otf](https://ocv.me/stuff/NotoSansCJKjp-Regular.otf) into it 

then, either use [ytdl-tui](https://github.com/9001/softchat/blob/hovedstraum/contrib/ytdl-tui.py) to download the vid+chat+emotes automatically, or:

```
python3 -m pip install --user softchat chat-downloader
python3 -m chat_downloader -o the.json -c cookies.txt youtu.be/3UV8OZj2olg 
python3 -m softchat --emote_font --emote_cache emotes the.json 
```

...and see #85 regarding cookies.txt if you're opting for the manual approach :>

**Comment by xenova** [comment]
> Will chat-downloader support youtube emote download?
> 
> It'll be nice to see it stored in ChatDownloader instance and available when exported.
> 
> Thank you!
> 
> e.g.
> 
> ```python
> x = ChatDownloader(...)
> 
> # Do some download stuff
> 
> x.emotes # {":hii:": "https://.../hii.png", ":hey:": "https.."}
> ```

Emote information is included in the messages, so what you could do is add to your "list of emotes" after a message comes in that contains the `emotes` key. Something like this, for example:
```python
import json
from chat_downloader import ChatDownloader

emote_dictionary = {}

url = 'https://www.youtube.com/watch?v=0GRsPTEG7Sk'
chat = ChatDownloader().get_chat(url, start_time=400, end_time=500)

for message in chat:
    for emote in message.get('emotes') or []:
        if emote['id'] not in emote_dictionary:
            emote_dictionary[emote['id']] = emote
            print('Added emote:', emote['name'])

print('All emote information:')
print(json.dumps(emote_dictionary, indent=4))
```

Let me know if you have any other questions 😃
