### ISSUE TITLE
Message groups and commands question

### ISSUE THREAD

**Issue by craxxon** [xenova/chat-downloader#92]
I am trying to log moderation information for a channel.  I have bans and deleted messages selected as "message-groups" and it works but does not show what the deleted message was. Right now it shows the message ID for deleted and user ID for bans and that is great, but I was wondering if there are commands I have not thought of or found.

Is there a command to log both that the message was deleted as well as the user and timestamp to one csv log?  No big deal if you can't, but was curious.

If I run one instance to log the whole chat and another for the bans and deletes, I think I can script something to cross reference both files and get the result.  I was wondering if there was an easier way, as this is probably a common use for logging chat.

Also, thank you so much for writing such a useful program!  It is obvious it has a lot of work put into it and is very useful, excellent job.

**Comment by xenova** [comment]
For these "custom programs/use-cases", I would recommend implementing a solution using the python module. Unfortunately, it would be impractical to include all possible use-cases in the command-line program. Of course, if more people feel this feature is necessary, I can add it to the command-line program. I have been trying to document the python module as much as possible, but I still have a long way to go. https://chat-downloader.readthedocs.io/en/latest/

An example of how to implement this would be as follows:
YouTube sends a "delete message" command (containing the ID of the message) whenever a message must be remove from chat. So, to see what message was deleted (i.e., the text), you could keep track of the messages that were sent and then match the deleted message ID to the corresponding message that was previously sent. 

Hope this helps!

**Comment by xenova** [comment]
I had some time on my hands, so I decided to give an example of what this could look like:

```python
from chat_downloader import ChatDownloader
from chat_downloader.utils import multi_get

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url, message_groups='all')

previous_messages = {}
for message in chat:
    message_id = message.get('message_id')
    if message_id:  # Save message
        previous_messages[message_id] = message

    # Check if a message should be removed, or a user should be banned
    message_type = message.get('message_type')
    if message_type == 'deleted_message':
        target_message_id = message.get('target_message_id')
        original_message = previous_messages.get(target_message_id)

        if not original_message:
            continue  # Message to be deleted is not in chat

        author_name = multi_get(original_message, 'author', 'name')
        author_id = multi_get(original_message, 'author', 'id')
        original_message = original_message.get('message')
        print('Message sent by', author_name, '({})'.format(
            author_id), 'was removed:', original_message)

    elif message_type == 'ban_user':
        print('User banned:', multi_get(message, 'author', 'id'))

```

running this would produce output similar to:
```
User banned: UCDlAGBjNEU0414ut-fGsWBQ
Message sent by T Ing (UCxGDJLKOQ-asgoSHSCsuO_A) was removed: 🍄👁🍄👁🍄👁
User banned: UCxGDJLKOQ-asgoSHSCsuO_A
Message sent by k.s  (UC-7Ww5R5DSQtxjArSDi-1oA) was removed: @nini TELL HER THAT I HATE HER
User banned: UCxVGH6SxT6He2zZU_1dT_qw
Message sent by Nicolo (UC-QKKASyPysuKCbY-Ex-2IQ) was removed: can I get a hold in the chat
Message sent by Nicolo (UC-QKKASyPysuKCbY-Ex-2IQ) was removed: can I get a hola in the chat
Message sent by Nicolo (UC-QKKASyPysuKCbY-Ex-2IQ) was removed: @you 🙂
```

---

Let me know if you have any further questions 👍
